/**
 * AppIcon — 1:1 port of the mobile semantic icon system (iconTokens.ts).
 * One icon family (Ionicons via react-icons/io5), one optical band,
 * outline = resting, filled = selected/active.
 */

import {
  IoAccessibilityOutline,
  IoAdd,
  IoAddCircle,
  IoAlertCircle,
  IoAlertCircleOutline,
  IoArrowBack,
  IoArrowForward,
  IoArrowUpCircle,
  IoArrowUpCircleOutline,
  IoBag,
  IoBagHandle,
  IoBagHandleOutline,
  IoBagOutline,
  IoBan,
  IoBanOutline,
  IoBookmark,
  IoBookmarkOutline,
  IoBulb,
  IoBulbOutline,
  IoCamera,
  IoCameraOutline,
  IoCard,
  IoCardOutline,
  IoCash,
  IoCashOutline,
  IoChatbubble,
  IoChatbubbleEllipses,
  IoChatbubbleEllipsesOutline,
  IoChatbubbleOutline,
  IoCheckmark,
  IoCheckmarkCircle,
  IoCheckmarkCircleOutline,
  IoChevronBack,
  IoChevronDown,
  IoChevronDownCircle,
  IoChevronForward,
  IoChevronUp,
  IoChevronUpCircle,
  IoClose,
  IoCloseCircle,
  IoCloseCircleOutline,
  IoColorPalette,
  IoColorPaletteOutline,
  IoCompass,
  IoCompassOutline,
  IoCreate,
  IoCreateOutline,
  IoCube,
  IoCubeOutline,
  IoDesktop,
  IoDesktopOutline,
  IoDocumentText,
  IoDocumentTextOutline,
  IoDownload,
  IoDownloadOutline,
  IoEllipsisHorizontal,
  IoEllipsisHorizontalCircle,
  IoEye,
  IoEyeOff,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFileTrayStacked,
  IoFileTrayStackedOutline,
  IoFlash,
  IoFlashOutline,
  IoFilter,
  IoFilterOutline,
  IoFingerPrint,
  IoFingerPrintOutline,
  IoFlag,
  IoFlagOutline,
  IoFlame,
  IoFlameOutline,
  IoFolderOpen,
  IoFolderOpenOutline,
  IoGlobe,
  IoGlobeOutline,
  IoGrid,
  IoGridOutline,
  IoHammer,
  IoHammerOutline,
  IoHardwareChip,
  IoHardwareChipOutline,
  IoHeart,
  IoHeartOutline,
  IoHelpCircle,
  IoHelpCircleOutline,
  IoHome,
  IoHomeOutline,
  IoImage,
  IoImageOutline,
  IoImages,
  IoImagesOutline,
  IoInformationCircle,
  IoInformationCircleOutline,
  IoKey,
  IoKeyOutline,
  IoLanguage,
  IoLanguageOutline,
  IoLayers,
  IoLayersOutline,
  IoLeaf,
  IoLeafOutline,
  IoLink,
  IoLinkOutline,
  IoLocation,
  IoLocationOutline,
  IoLogOut,
  IoLogOutOutline,
  IoLockClosed,
  IoLockClosedOutline,
  IoLockOpen,
  IoLockOpenOutline,
  IoMail,
  IoMailOutline,
  IoMailUnread,
  IoMailUnreadOutline,
  IoMenu,
  IoMic,
  IoMicOutline,
  IoMoon,
  IoMoonOutline,
  IoNewspaper,
  IoNewspaperOutline,
  IoNotifications,
  IoNotificationsOff,
  IoNotificationsOffOutline,
  IoNotificationsOutline,
  IoOptions,
  IoOptionsOutline,
  IoPause,
  IoPauseOutline,
  IoPeople,
  IoPeopleOutline,
  IoPerson,
  IoPersonAdd,
  IoPersonAddOutline,
  IoPersonOutline,
  IoPersonRemove,
  IoPersonRemoveOutline,
  IoPhonePortrait,
  IoPhonePortraitOutline,
  IoPin,
  IoPinOutline,
  IoPlay,
  IoPlayOutline,
  IoPricetag,
  IoPricetagOutline,
  IoPricetags,
  IoPricetagsOutline,
  IoReceipt,
  IoReceiptOutline,
  IoRefresh,
  IoRefreshOutline,
  IoRemove,
  IoRemoveOutline,
  IoRepeat,
  IoRepeatOutline,
  IoScan,
  IoScanOutline,
  IoSearch,
  IoSearchOutline,
  IoSend,
  IoSendOutline,
  IoSettings,
  IoSettingsOutline,
  IoShare,
  IoShareOutline,
  IoShield,
  IoShieldOutline,
  IoStar,
  IoStarOutline,
  IoStatsChart,
  IoStatsChartOutline,
  IoStop,
  IoStopOutline,
  IoStorefront,
  IoStorefrontOutline,
  IoSwapVertical,
  IoTime,
  IoTimeOutline,
  IoTrash,
  IoTrashOutline,
  IoTrendingUp,
  IoTrendingUpOutline,
  IoVideocam,
  IoVideocamOutline,
  IoWallet,
  IoWalletOutline,
  IoWarning,
  IoWarningOutline,
} from 'react-icons/io5';
import type { IconType } from 'react-icons';

/** Semantic names — mirror SemanticIconMap keys exactly. */
const ICONS = {
  home: { outline: IoHomeOutline, filled: IoHome },
  explore: { outline: IoSearchOutline, filled: IoSearch },
  search: { outline: IoSearchOutline, filled: IoSearch },
  create: { outline: IoAdd, filled: IoAddCircle },
  inbox: { outline: IoChatbubbleEllipsesOutline, filled: IoChatbubbleEllipses },
  chat: { outline: IoChatbubbleOutline, filled: IoChatbubble },
  profile: { outline: IoPersonOutline, filled: IoPerson },
  settings: { outline: IoSettingsOutline, filled: IoSettings },
  heart: { outline: IoHeartOutline, filled: IoHeart },
  bookmark: { outline: IoBookmarkOutline, filled: IoBookmark },
  share: { outline: IoShareOutline, filled: IoShare },
  comment: { outline: IoChatbubbleOutline, filled: IoChatbubble },
  sparkles: { outline: IoBulbOutline, filled: IoBulb },
  star: { outline: IoStarOutline, filled: IoStar },
  eye: { outline: IoEyeOutline, filled: IoEye },
  eyeOff: { outline: IoEyeOffOutline, filled: IoEyeOff },
  cart: { outline: IoBagHandleOutline, filled: IoBagHandle },
  pricetag: { outline: IoPricetagOutline, filled: IoPricetag },
  wallet: { outline: IoWalletOutline, filled: IoWallet },
  card: { outline: IoCardOutline, filled: IoCard },
  receipt: { outline: IoReceiptOutline, filled: IoReceipt },
  box: { outline: IoCubeOutline, filled: IoCube },
  auction: { outline: IoHammerOutline, filled: IoHammer },
  trending: { outline: IoTrendingUpOutline, filled: IoTrendingUp },
  camera: { outline: IoCameraOutline, filled: IoCamera },
  image: { outline: IoImageOutline, filled: IoImage },
  images: { outline: IoImagesOutline, filled: IoImages },
  play: { outline: IoPlayOutline, filled: IoPlay },
  pause: { outline: IoPauseOutline, filled: IoPause },
  videocam: { outline: IoVideocamOutline, filled: IoVideocam },
  layers: { outline: IoLayersOutline, filled: IoLayers },
  scan: { outline: IoScanOutline, filled: IoScan },
  shieldCheck: { outline: IoCheckmarkCircleOutline, filled: IoCheckmarkCircle },
  lock: { outline: IoLockClosedOutline, filled: IoLockClosed },
  lockOpen: { outline: IoLockOpenOutline, filled: IoLockOpen },
  verified: { outline: IoCheckmarkCircleOutline, filled: IoCheckmarkCircle },
  warning: { outline: IoWarningOutline, filled: IoWarning },
  alert: { outline: IoAlertCircleOutline, filled: IoAlertCircle },
  info: { outline: IoInformationCircleOutline, filled: IoInformationCircle },
  help: { outline: IoHelpCircleOutline, filled: IoHelpCircle },
  leaf: { outline: IoLeafOutline, filled: IoLeaf },
  accessibility: { outline: IoAccessibilityOutline, filled: IoAccessibilityOutline },
  analytics: { outline: IoStatsChartOutline, filled: IoStatsChart },
  feed: { outline: IoNewspaperOutline, filled: IoNewspaper },
  compass: { outline: IoCompassOutline, filled: IoCompass },
  shield: { outline: IoShieldOutline, filled: IoShield },
  key: { outline: IoKeyOutline, filled: IoKey },
  link: { outline: IoLinkOutline, filled: IoLink },
  fingerprint: { outline: IoFingerPrintOutline, filled: IoFingerPrint },
  download: { outline: IoDownloadOutline, filled: IoDownload },
  mail: { outline: IoMailOutline, filled: IoMail },
  globe: { outline: IoGlobeOutline, filled: IoGlobe },
  palette: { outline: IoColorPaletteOutline, filled: IoColorPalette },
  people: { outline: IoPeopleOutline, filled: IoPeople },
  repeat: { outline: IoRepeatOutline, filled: IoRepeat },
  document: { outline: IoDocumentTextOutline, filled: IoDocumentText },
  folder: { outline: IoFolderOpenOutline, filled: IoFolderOpen },
  ban: { outline: IoBanOutline, filled: IoBan },
  phone: { outline: IoPhonePortraitOutline, filled: IoPhonePortrait },
  desktop: { outline: IoDesktopOutline, filled: IoDesktop },
  chip: { outline: IoHardwareChipOutline, filled: IoHardwareChip },
  tag: { outline: IoPricetagOutline, filled: IoPricetag },
  mailUnread: { outline: IoMailUnreadOutline, filled: IoMailUnread },
  flag: { outline: IoFlagOutline, filled: IoFlag },
  zap: { outline: IoFlashOutline, filled: IoFlash },
  pin: { outline: IoPinOutline, filled: IoPin },
  notificationsOff: { outline: IoNotificationsOffOutline, filled: IoNotificationsOff },
  arrowUp: { outline: IoArrowUpCircleOutline, filled: IoArrowUpCircle },
  close: { outline: IoClose, filled: IoCloseCircle },
  closeCircle: { outline: IoCloseCircleOutline, filled: IoCloseCircle },
  check: { outline: IoCheckmark, filled: IoCheckmarkCircle },
  plus: { outline: IoAdd, filled: IoAddCircle },
  trash: { outline: IoTrashOutline, filled: IoTrash },
  edit: { outline: IoCreateOutline, filled: IoCreate },
  filter: { outline: IoFilterOutline, filled: IoFilter },
  options: { outline: IoOptionsOutline, filled: IoOptions },
  refresh: { outline: IoRefreshOutline, filled: IoRefresh },
  more: { outline: IoEllipsisHorizontal, filled: IoEllipsisHorizontalCircle },
  back: { outline: IoChevronBack, filled: IoArrowBack },
  forward: { outline: IoChevronForward, filled: IoArrowForward },
  chevronDown: { outline: IoChevronDown, filled: IoChevronDownCircle },
  chevronUp: { outline: IoChevronUp, filled: IoChevronUpCircle },
  clock: { outline: IoTimeOutline, filled: IoTime },
  location: { outline: IoLocationOutline, filled: IoLocation },
  notifications: { outline: IoNotificationsOutline, filled: IoNotifications },
  menu: { outline: IoMenu, filled: IoMenu },
  sort: { outline: IoSwapVertical, filled: IoSwapVertical },
  remove: { outline: IoRemoveOutline, filled: IoRemove },
  bag: { outline: IoBagOutline, filled: IoBag },
  offer: { outline: IoPricetagsOutline, filled: IoPricetags },
  payout: { outline: IoCashOutline, filled: IoCash },
  send: { outline: IoSendOutline, filled: IoSend },
  follow: { outline: IoPersonAddOutline, filled: IoPersonAdd },
  personAdd: { outline: IoPersonAddOutline, filled: IoPersonAdd },
  personRemove: { outline: IoPersonRemoveOutline, filled: IoPersonRemove },
  mic: { outline: IoMicOutline, filled: IoMic },
  stop: { outline: IoStopOutline, filled: IoStop },
  moon: { outline: IoMoonOutline, filled: IoMoon },
  language: { outline: IoLanguageOutline, filled: IoLanguage },
  fire: { outline: IoFlameOutline, filled: IoFlame },
  store: { outline: IoStorefrontOutline, filled: IoStorefront },
  exit: { outline: IoLogOutOutline, filled: IoLogOut },
  inventory: { outline: IoFileTrayStackedOutline, filled: IoFileTrayStacked },
  dashboard: { outline: IoGridOutline, filled: IoGrid },
} satisfies Record<string, { outline: IconType; filled: IconType }>;

export type AppIconName = keyof typeof ICONS;

interface IconProps {
  name: AppIconName;
  /** filled = selected/active/saved. Outline is the resting default. */
  filled?: boolean;
  size?: number;
  className?: string;
  /** Decorative by default — pass a label for standalone meaningful icons. */
  'aria-label'?: string;
}

export function Icon({ name, filled = false, size = 22, className, 'aria-label': ariaLabel }: IconProps) {
  const pair = ICONS[name] ?? ICONS.info;
  const Cmp = filled ? pair.filled : pair.outline;
  return (
    <Cmp
      size={size}
      className={className}
      aria-hidden={ariaLabel ? undefined : true}
      aria-label={ariaLabel}
      focusable="false"
    />
  );
}
