import type { ConversationContext } from './conversationContext';

export interface MessageReaction {
  emoji: string;
  userIds: string[];
  /** Derived convenience: userIds.length. Populated by mappers so the UI
   *  can render reaction counts without recomputing. */
  count?: number;
  /** Derived convenience: whether the current user is in userIds. */
  reactedByMe?: boolean;
}

export interface Message {
  id: string;
  senderId: string;
  text?: string;
  offerPrice?: number;
  originalPrice?: number;
  offerStatus?: 'pending' | 'accepted' | 'declined' | 'countered' | 'expired' | 'cancelled';
  isSystem?: boolean;
  systemTitle?: string;
  timestamp: string;
  itemImage?: string;
  type?: 'text' | 'offer' | 'offer_declined' | 'purchase_status' | 'system' | 'commerce_state' | 'voice' | 'media' | 'listing_share' | 'document';
  sender?: 'me' | 'other' | 'system';
  listing?: {
    id: string;
    title: string;
    price: number;
    originalPrice?: number;
    images?: string[];
    image?: string;
    brand?: string | null;
    sellerId?: string | null;
    size?: string;
    condition?: string;
    sellerUsername?: string;
    sellerRating?: number;
    isSold?: boolean;
  };
  documentUri?: string;
  documentName?: string;
  documentMimeType?: string;
  offer?: {
    offerId?: string;
    originalPrice?: number;
    offerPrice?: number;
    /** Alias for offerPrice — used by MarketplaceChatCard and legacy consumers. */
    price?: number;
    amount?: number;
    status?: 'pending' | 'accepted' | 'declined' | 'countered' | 'expired' | 'cancelled';
    expiresAt?: string;
    counterRound?: number;
    buyerId?: string;
    sellerId?: string;
    /** Author of the pending offer — the card needs it to pick the
     *  role-correct exit action (buyer cancels, seller declines). */
    offeredByUserId?: string;
    listingId?: string;
    itemId?: string;
    listingTitle?: string;
  };
  reactions?: MessageReaction[];
  replyToMessageId?: string;
  mediaUri?: string;
  mediaType?: 'image' | 'video';
  /** Poster still for video media — the mediaUri may be an HLS playlist no
   *  image loader can decode; bubbles and media grids render this instead. */
  posterUri?: string;
  uploadStatus?: 'uploading' | 'failed' | 'sent';
  // Voice messages — report 19.
  voiceUri?: string;
  voiceDurationMs?: number;
  voiceWaveform?: number[];
  voiceContainer?: 'm4a' | 'ogg' | 'webm' | 'mp4';
  voiceCodec?: 'aac' | 'opus' | 'mp3';
  voiceModerationState?: 'pending' | 'allowed' | 'limited' | 'blocked';
  /** ID of the bot/agent that authored this message (agent conversations). */
  botId?: string;
  /** True when the message was generated in demo mode (clearly labelled). */
  isDemo?: boolean;
  /** Delivery lifecycle for optimistic/synced messages. */
  status?: 'sending' | 'sent' | 'failed' | 'draft' | 'reconciling';
  /** True when the message was edited after creation. */
  isEdited?: boolean;
  /** True when the message was deleted for everyone. */
  isDeleted?: boolean;
  /** Stable client-generated id for idempotent message creation. */
  clientMessageId?: string;
  /** Server-assigned edit version for conflict detection. */
  editVersion?: number;
  /** When the message was last edited. */
  editedAt?: string | null;
  /** When the message was deleted for everyone. */
  deletedForEveryoneAt?: string | null;
  /** Read receipt state. */
  readStatus?: 'sending' | 'sent' | 'delivered' | 'read';
  /** User IDs who have read this message (durable per-message receipts). */
  readBy?: string[];
  /** Whether the current user has read this message (their own perspective). */
  isReadByMe?: boolean;
  commerceState?: {
    stateType: CommerceStateType;
    orderId: string;
    orderShortId?: string;
    itemTitle?: string;
    itemImage?: string | null;
    trackingNumber?: string | null;
    carrier?: string | null;
    /** Dispatch-extension proposal snapshot (extension_requested cards). */
    extensionDays?: number;
    proposedShipBy?: string;
    /** Refund amount (GBP) on order_refunded / order_partially_refunded cards. */
    refundedAmountGbp?: number;
  };
  /** Display label for the sender (username / bot name / "System"). */
  senderLabel?: string;
  /** Alias for `timestamp` — used by chat hooks and UI components for date
   *  separators, sorting, and age calculations. Mappers populate both. */
  date?: string;
  /** Voice transcription receipt (joined from voice_transcriptions). */
  voiceTranscription?: {
    id: string;
    state: 'queued' | 'processing' | 'complete' | 'failed_retryable' | 'failed_final' | 'unsupported';
    text: string | null;
    language: string | null;
    failureReason: string | null;
    derived: true;
  };
  /** True when this message was generated by a deployed AI agent (demo). */
  isAgent?: boolean;
  /** Ionicon name for the agent avatar glyph (only set for agent messages). */
  agentAvatar?: string;
  /** Threaded reply preview — resolved by the caller from replyToMessageId. */
  replyTo?: { senderName: string; text: string } | null;
  /** Server-authoritative scam warning flag — set when the backend scam
   *  scanner detects medium-severity off-platform contact patterns. */
  scamWarning?: boolean;
  /** True when this message is pinned for the conversation by an admin. */
  isPinned?: boolean;
  /** ISO timestamp when the message was pinned. */
  pinnedAt?: string;
  /** Snapchat-style "Saved in chat" — shared, negotiated persistence.
   *  True while at least one participant's save remains; both parties
   *  see the marker regardless of who saved. */
  isSavedInChat?: boolean;
  /** User IDs that currently have this message saved in chat (shared
   *  attribution — the set is identical for both participants). */
  savedBy?: string[];
  /** ISO timestamp of the first save. */
  savedAt?: string;
  /** Poll data attached to a poll-type message. */
  poll?: ChatPollData;
}

export interface ChatPollData {
  id: string;
  question: string;
  options: string[];
  allowMultiple: boolean;
  isAnonymous: boolean;
  closesAt?: string;
  voteCounts: number[];
  myVotes: number[];
}

export type { ConversationContext } from './conversationContext';

export type ConversationType = 'dm' | 'group';

export interface Conversation {
  id: string;
  type: ConversationType;
  title?: string;
  description?: string;
  /** Circular group avatar / profile picture (small, 1:1). */
  avatar?: string;
  /** Wide cover photo banner shown at the top of group info (WhatsApp/Telegram pattern). */
  coverPhoto?: string;
  sellerId?: string;
  itemId?: string;
  ownerId?: string;
  creatorId?: string;
  createdAt?: string;
  participantIds?: string[];
  participantProfiles?: Array<{
    id: string;
    username: string;
    displayName?: string | null;
    avatar?: string | null;
    emailVerified?: boolean;
    /** Identity/KYC verification — drives the verified badge, not email. */
    identityVerified?: boolean;
  }>;
  botIds?: string[];
  lastMessage: string;
  lastMessageTime: string;
  unread: boolean;
  /** Server-derived count of unread messages (0 when fully read). */
  unreadCount?: number;
  messages: Message[];
  isPinned?: boolean;
  draftText?: string;
  /** Member roles: userId → 'owner' | 'admin' | 'member'. Populated from backend. */
  memberRoles?: Record<string, 'owner' | 'admin' | 'member'>;
  /** P0.12: Per-user conversation state — hydrated from backend, not local-only. */
  isMuted?: boolean;
  /** Graduated moderation ladder — viewer has blocked the DM counterparty. */
  isBlocked?: boolean;
  /** Graduated moderation ladder — viewer has restricted the DM counterparty
   *  (their messages land in requests; no read receipts/typing flow back). */
  isRestricted?: boolean;
  /** Viewer has user-level-muted the DM counterparty — suppresses their
   *  message notifications across all shared conversations. Distinct from
   *  `isMuted`, which is the per-conversation notification mute. */
  isAuthorMuted?: boolean;
  /** Server-emitted alias carrying the same restrict edge as isRestricted. */
  isAuthorRestricted?: boolean;
  isArchived?: boolean;
  requestStatus?: 'pending' | 'accepted' | 'declined';
  markedUnread?: boolean;
  /** ISO timestamp of the last read receipt for this conversation. */
  lastReadAt?: string;
  /** Authoritative transaction context — listing, offer, order, protection.
   *  Derived server-side from the database; null for non-marketplace chats. */
  context?: ConversationContext;
}

/** Order lifecycle states the in-thread commerce card can render — mirrors
 *  the backend emitter (backend/api/src/lib/orderChatCards.ts) which places
 *  the snapshot under `metadata.commerceState`. */
export type CommerceStateType =
  | 'order_placed'
  | 'payment_confirmed'
  | 'label_created'
  | 'order_shipped'
  | 'order_in_transit'
  | 'order_delivered'
  | 'delivery_confirm_prompt'
  | 'feedback_prompt'
  | 'extension_requested'
  | 'order_cancelled'
  | 'order_refunded'
  | 'order_partially_refunded';

const COMMERCE_STATE_TYPES: ReadonlySet<string> = new Set<CommerceStateType>([
  'order_placed',
  'payment_confirmed',
  'label_created',
  'order_shipped',
  'order_in_transit',
  'order_delivered',
  'delivery_confirm_prompt',
  'feedback_prompt',
  'extension_requested',
  'order_cancelled',
  'order_refunded',
  'order_partially_refunded',
]);

/**
 * Parse the `metadata.commerceState` snapshot carried by system-authored
 * order lifecycle messages into the domain `commerceState` field consumed by
 * ChatCommerceCard → MarketplaceChatCard. Returns undefined when the metadata
 * is absent or malformed — the message then falls back to a plain system row.
 */
export function parseMessageCommerceState(
  metadata: Record<string, unknown> | null | undefined,
): Message['commerceState'] | undefined {
  const raw = metadata?.commerceState;
  if (!raw || typeof raw !== 'object') return undefined;
  const state = raw as Record<string, unknown>;
  if (typeof state.stateType !== 'string' || typeof state.orderId !== 'string') {
    return undefined;
  }
  if (!COMMERCE_STATE_TYPES.has(state.stateType)) {
    return undefined;
  }
  return {
    stateType: state.stateType as CommerceStateType,
    orderId: state.orderId,
    orderShortId: typeof state.orderShortId === 'string' ? state.orderShortId : undefined,
    itemTitle: typeof state.itemTitle === 'string' ? state.itemTitle : undefined,
    itemImage: typeof state.itemImage === 'string' ? state.itemImage : state.itemImage === null ? null : undefined,
    trackingNumber: typeof state.trackingNumber === 'string' ? state.trackingNumber : state.trackingNumber === null ? null : undefined,
    carrier: typeof state.carrier === 'string' ? state.carrier : state.carrier === null ? null : undefined,
    extensionDays: typeof state.extensionDays === 'number' ? state.extensionDays : undefined,
    proposedShipBy: typeof state.proposedShipBy === 'string' ? state.proposedShipBy : undefined,
    refundedAmountGbp: typeof state.refundedAmountGbp === 'number' ? state.refundedAmountGbp : undefined,
  };
}
