/**
 * Shared chat controller types and helpers.
 *
 * These types are extracted from ChatScreen.tsx so that the controller hooks
 * (useConversationMessages, useConversationComposer, etc.) can share the same
 * Message shape without circular imports.
 */

export type MsgType =
  | "text"
  | "offer"
  | "offer_declined"
  | "purchase_status"
  | "media"
  | "system"
  | "commerce_state"
  | "voice";

export interface Message {
  id: string;

  type: MsgType;

  sender: "me" | "them";

  senderId?: string;

  senderLabel?: string;

  text?: string;

  isSystem?: boolean;

  systemTitle?: string;

  offer?: {
    offerId?: string;
    price: number;
    originalPrice: number;
    status?:
      | "pending"
      | "declined"
      | "countered"
      | "accepted"
      | "expired"
      | "cancelled";
    /** ISO date string when the offer expires */
    expiresAt?: string;
    /** Counter-offer chain depth (0 = initial, 1 = first counter, etc.) */
    counterRound?: number;
  };

  date?: string;

  replyToMessageId?: string;

  reactions?: Array<{ emoji: string; count: number; reactedByMe: boolean }>;

  mediaUri?: string;

  mediaType?: "image" | "video";

  voiceUri?: string;

  voiceDurationMs?: number;

  voiceWaveform?: number[];

  commerceState?: {
    stateType:
      | "order_placed"
      | "payment_confirmed"
      | "order_shipped"
      | "order_in_transit"
      | "order_delivered"
      | "order_cancelled"
      | "order_refunded";
    orderId: string;
    orderShortId?: string;
    itemTitle?: string;
    itemImage?: string | null;
    trackingNumber?: string | null;
    carrier?: string | null;
  };

  uploadStatus?: "uploading" | "failed" | "sent";

  status?: "sending" | "sent" | "failed" | "draft";

  readStatus?: "sending" | "sent" | "delivered" | "read";

  /** True when this message was generated by a deployed AI agent (demo). */
  isAgent?: boolean;

  /** Ionicon name for the agent avatar glyph (only set for agent messages). */
  agentAvatar?: string;
}

export const INITIAL_MESSAGES: Message[] = [];

// Context-aware default quick replies shown when user hasn't configured custom ones
export const DEFAULT_SELLER_QUICK_REPLIES = [
  "Thanks for your interest!",
  "Yes, it's still available.",
  "I can ship within 2 business days.",
  "Any questions about the item?",
];

export const DEFAULT_BUYER_QUICK_REPLIES = [
  "Is this still available?",
  "Can I make an offer?",
  "What's your best price?",
  "Could you share more photos?",
];

export function parseMessageDate(dateStr: string): Date | null {
  const legacyMatch = dateStr.match(
    /^(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2}):(\d{2}))?$/,
  );
  const d = legacyMatch
    ? new Date(
        Number(legacyMatch[3]),
        Number(legacyMatch[2]) - 1,
        Number(legacyMatch[1]),
        Number(legacyMatch[4] ?? 12),
        Number(legacyMatch[5] ?? 0),
      )
    : new Date(dateStr);
  return Number.isNaN(d.getTime()) ? null : d;
}

export function formatDateSeparator(dateStr: string): string | null {
  const d = parseMessageDate(dateStr);
  if (!d) return null;
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const input = new Date(d.getFullYear(), d.getMonth(), d.getDate());
  const diffDays = Math.round((today.getTime() - input.getTime()) / 86400000);
  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "Yesterday";
  if (diffDays < 7) {
    return d.toLocaleDateString(undefined, { weekday: "short" });
  }
  return d.toLocaleDateString(undefined, {
    weekday: "short",
    day: "numeric",
    month: "short",
  });
}

export function formatMessageTime(dateStr?: string): string | undefined {
  if (!dateStr) return undefined;
  const hasExplicitTime = /T\d{2}:\d{2}|\b\d{1,2}:\d{2}\b/.test(dateStr);
  if (!hasExplicitTime) return undefined;
  const d = parseMessageDate(dateStr);
  if (!d) return undefined;
  return d.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" });
}
