import { createStableId } from '../../../utils/createStableId';
import { baseLayer, page, type CreatorTemplate } from './shared';

export const LOOK_TEMPLATES: CreatorTemplate[] = [
  {
    id: 'tpl_look_single_photo',
    name: 'Single Photo',
    type: 'look',
    description: 'Editorial single-photo layout',
    category: 'editorial',
    styleTags: ['Minimal', 'Archive'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 0.75, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.85, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Editorial Look', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_outfit_board',
    name: 'Outfit Board',
    type: 'look',
    description: 'Three-piece outfit grid',
    category: 'editorial',
    styleTags: ['Streetwear', 'Techwear'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#f5f5f5' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.4, height: 0.4, x: 0.3, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.4, height: 0.4, x: 0.7, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.4, height: 0.4, x: 0.5, y: 0.7, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Outfit Board', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_product_grid',
    name: 'Product Grid',
    type: 'look',
    description: 'Minimal product grid layout',
    category: 'editorial',
    styleTags: ['Minimal'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 0.8, background: { type: 'color', value: '#ffffff' } },
      pages: [page([
        { ...baseLayer(createStableId('product'), 1), type: 'product', width: 0.3, height: 0.15, x: 0.3, y: 0.25, payload: { listingId: '', snapshotTitle: 'Item 1', snapshotPriceGbp: 0, availability: 'active' } },
        { ...baseLayer(createStableId('product'), 2), type: 'product', width: 0.3, height: 0.15, x: 0.7, y: 0.25, payload: { listingId: '', snapshotTitle: 'Item 2', snapshotPriceGbp: 0, availability: 'active' } },
        { ...baseLayer(createStableId('product'), 3), type: 'product', width: 0.3, height: 0.15, x: 0.3, y: 0.5, payload: { listingId: '', snapshotTitle: 'Item 3', snapshotPriceGbp: 0, availability: 'active' } },
        { ...baseLayer(createStableId('product'), 4), type: 'product', width: 0.3, height: 0.15, x: 0.7, y: 0.5, payload: { listingId: '', snapshotTitle: 'Item 4', snapshotPriceGbp: 0, availability: 'active' } },
      ])],
      metadata: { title: 'Product Grid', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_magazine',
    name: 'Magazine',
    type: 'look',
    description: 'Magazine-style editorial layout',
    category: 'editorial',
    styleTags: ['Archive', 'Vintage'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 0.75, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.7, y: 0.4, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.8, height: 0.1, y: 0.85, payload: { text: 'EDITORIAL', textStyle: 'headline', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
      ])],
      metadata: { title: 'Magazine Look', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_colour_story',
    name: 'Colour Story',
    type: 'look',
    description: 'Colour-focused story layout',
    category: 'editorial',
    styleTags: ['Gorpcore', 'Vintage'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#2c2c2c' } },
      pages: [page([
        { ...baseLayer(createStableId('decorative'), 1), type: 'decorative', width: 0.5, height: 0.5, x: 0.3, y: 0.3, payload: { shape: 'circle', color: '#9A6B7A', opacity: 0.8 } },
        { ...baseLayer(createStableId('decorative'), 2), type: 'decorative', width: 0.4, height: 0.4, x: 0.7, y: 0.7, payload: { shape: 'circle', color: '#215634', opacity: 0.6 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.6, height: 0.08, y: 0.9, payload: { text: 'Colour Story', textStyle: 'editorial', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
      ])],
      metadata: { title: 'Colour Story', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  // ── Instagram Layout-style grid presets ──────────────────────────
  {
    id: 'tpl_look_split_2',
    name: 'Split 2',
    type: 'look',
    description: 'Two-photo vertical split',
    category: 'editorial',
    styleTags: ['Streetwear', 'Archive'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.48, height: 0.96, x: 0.25, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.48, height: 0.96, x: 0.75, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Split Look', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_horizontal_3',
    name: 'Triple',
    type: 'look',
    description: 'Three-photo horizontal strip',
    category: 'editorial',
    styleTags: ['Streetwear', 'Techwear'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.31, height: 0.96, x: 0.17, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.31, height: 0.96, x: 0.5, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.31, height: 0.96, x: 0.83, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Triple Look', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_grid_4',
    name: 'Grid 4',
    type: 'look',
    description: 'Four-photo grid collage',
    category: 'editorial',
    styleTags: ['Streetwear', 'Gorpcore'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.47, height: 0.47, x: 0.26, y: 0.26, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.47, height: 0.47, x: 0.74, y: 0.26, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.47, height: 0.47, x: 0.26, y: 0.74, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 4), type: 'media', width: 0.47, height: 0.47, x: 0.74, y: 0.74, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Grid Look', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_grid_6',
    name: 'Grid 6',
    type: 'look',
    description: 'Six-photo grid collage',
    category: 'editorial',
    styleTags: ['Gorpcore', 'Techwear'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.31, height: 0.31, x: 0.17, y: 0.17, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.31, height: 0.31, x: 0.5, y: 0.17, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.31, height: 0.31, x: 0.83, y: 0.17, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 4), type: 'media', width: 0.31, height: 0.31, x: 0.17, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 5), type: 'media', width: 0.31, height: 0.31, x: 0.5, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 6), type: 'media', width: 0.31, height: 0.31, x: 0.83, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Grid 6 Look', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_feature_split',
    name: 'Feature',
    type: 'look',
    description: 'Large feature photo with two side photos',
    category: 'editorial',
    styleTags: ['Archive', 'Vintage'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.6, height: 0.96, x: 0.32, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.34, height: 0.47, x: 0.82, y: 0.26, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.34, height: 0.47, x: 0.82, y: 0.74, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Feature Look', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  // ── Instagram parity: extended look presets ───────────────────────
  {
    id: 'tpl_look_dual_photo',
    name: 'Dual Photo',
    type: 'look',
    description: 'Side-by-side comparison layout',
    category: 'editorial',
    styleTags: ['Minimal', 'Archive'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.48, height: 0.9, x: 0.26, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.48, height: 0.9, x: 0.74, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Dual Photo', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_portrait_strip',
    name: 'Portrait Strip',
    type: 'look',
    description: 'Vertical strip of three photos',
    category: 'editorial',
    styleTags: ['Vintage', 'Archive'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 0.8, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.7, height: 0.3, x: 0.5, y: 0.18, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.7, height: 0.3, x: 0.5, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.7, height: 0.3, x: 0.5, y: 0.82, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Portrait Strip', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_checkerboard',
    name: 'Checkerboard',
    type: 'look',
    description: '2x2 grid with alternating media and colour',
    category: 'editorial',
    styleTags: ['Streetwear', 'Vintage'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#C9A46A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.47, height: 0.47, x: 0.26, y: 0.26, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('decorative'), 2), type: 'decorative', width: 0.47, height: 0.47, x: 0.74, y: 0.26, payload: { shape: 'square', color: '#1a1a1a', opacity: 1 } },
        { ...baseLayer(createStableId('decorative'), 3), type: 'decorative', width: 0.47, height: 0.47, x: 0.26, y: 0.74, payload: { shape: 'square', color: '#1a1a1a', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 4), type: 'media', width: 0.47, height: 0.47, x: 0.74, y: 0.74, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Checkerboard', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_diagonal_split',
    name: 'Diagonal Split',
    type: 'look',
    description: 'Diagonal split two-photo layout',
    category: 'editorial',
    styleTags: ['Techwear', 'Streetwear'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.7, height: 0.7, x: 0.35, y: 0.35, rotation: -15, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.7, height: 0.7, x: 0.65, y: 0.65, rotation: 15, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('decorative'), 3), type: 'decorative', width: 1.2, height: 0.02, x: 0.5, y: 0.5, rotation: 45, payload: { shape: 'line', color: '#C9A46A', opacity: 1 } },
      ])],
      metadata: { title: 'Diagonal Split', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_circle_frame',
    name: 'Circle Frame',
    type: 'look',
    description: 'Central circular photo with border',
    category: 'editorial',
    styleTags: ['Minimal', 'Vintage'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#f5f5f5' } },
      pages: [page([
        { ...baseLayer(createStableId('decorative'), 1), type: 'decorative', width: 0.7, height: 0.7, x: 0.5, y: 0.5, payload: { shape: 'circle', color: '#C9A46A', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.6, height: 0.6, x: 0.5, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Circle Frame', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_film_strip',
    name: 'Film Strip',
    type: 'look',
    description: 'Horizontal film strip with three photos',
    category: 'editorial',
    styleTags: ['Vintage', 'Archive'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1.5, background: { type: 'color', value: '#0d0d0d' } },
      pages: [page([
        { ...baseLayer(createStableId('decorative'), 1), type: 'decorative', width: 0.96, height: 0.5, x: 0.5, y: 0.5, payload: { shape: 'square', color: '#1a1a1a', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.28, height: 0.4, x: 0.2, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.28, height: 0.4, x: 0.5, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 4), type: 'media', width: 0.28, height: 0.4, x: 0.8, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Film Strip', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_polaroid',
    name: 'Polaroid',
    type: 'look',
    description: 'Polaroid-style frame with caption space',
    category: 'editorial',
    styleTags: ['Vintage'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#2c2c2c' } },
      pages: [page([
        { ...baseLayer(createStableId('decorative'), 1), type: 'decorative', width: 0.7, height: 0.85, x: 0.5, y: 0.5, payload: { shape: 'square', color: '#ffffff', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.6, height: 0.6, x: 0.5, y: 0.4, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.6, height: 0.06, x: 0.5, y: 0.82, payload: { text: 'Caption', textStyle: 'handwritten', textColor: '#1a1a1a', alignment: 'center', opacity: 1 } },
      ])],
      metadata: { title: 'Polaroid', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_magazine_cover',
    name: 'Magazine Cover',
    type: 'look',
    description: 'Full magazine cover with title and subtitle',
    category: 'editorial',
    styleTags: ['Archive', 'Vintage'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 0.75, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.75, x: 0.5, y: 0.45, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.85, height: 0.12, x: 0.5, y: 0.1, payload: { text: 'VOGUE', textStyle: 'poster', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.75, height: 0.06, x: 0.5, y: 0.92, payload: { text: 'The Style Issue', textStyle: 'compact', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
      ])],
      metadata: { title: 'Magazine Cover', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_collage',
    name: 'Collage',
    type: 'look',
    description: 'Free-form collage with four overlapping photos',
    category: 'editorial',
    styleTags: ['Streetwear', 'Gorpcore'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#f5f5f5' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.45, height: 0.45, x: 0.3, y: 0.3, rotation: -8, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.45, height: 0.45, x: 0.7, y: 0.35, rotation: 6, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.45, height: 0.45, x: 0.35, y: 0.7, rotation: 4, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 4), type: 'media', width: 0.45, height: 0.45, x: 0.7, y: 0.72, rotation: -5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Collage', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_split_3',
    name: 'Split 3',
    type: 'look',
    description: 'Three-way horizontal split',
    category: 'editorial',
    styleTags: ['Streetwear', 'Techwear'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#0A0A0A' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.32, height: 0.96, x: 0.17, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.32, height: 0.96, x: 0.5, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.32, height: 0.96, x: 0.83, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Split 3', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_look_feature_stack',
    name: 'Feature Stack',
    type: 'look',
    description: 'Stacked feature with one large and two small photos',
    category: 'editorial',
    styleTags: ['Minimal', 'Archive'],
    build: () => ({
      id: createStableId('doc'),
      type: 'look',
      version: 1,
      canvas: { aspectRatio: 0.8, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.55, x: 0.5, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.41, height: 0.3, x: 0.27, y: 0.78, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.41, height: 0.3, x: 0.73, y: 0.78, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ])],
      metadata: { title: 'Feature Stack', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
];
