import { createStableId } from '../../../utils/createStableId';
import { baseLayer, page, type CreatorTemplate } from './shared';

export const POSTER_TEMPLATES: CreatorTemplate[] = [
  {
    id: 'tpl_poster_announcement',
    name: 'Announcement',
    type: 'poster',
    description: 'Photo announcement poster',
    category: 'announcement',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.6, y: 0.35, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.8, height: 0.1, y: 0.8, payload: { text: 'New Drop', textStyle: 'headline', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
      ], 5000)],
      metadata: { title: 'Announcement', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_product_spotlight',
    name: 'Product Spotlight',
    type: 'poster',
    description: 'Spotlight a single product',
    category: 'featured',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#0d0d0d' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.55, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('product'), 2), type: 'product', width: 0.6, height: 0.12, y: 0.75, payload: { listingId: '', snapshotTitle: 'Featured Item', snapshotPriceGbp: 49, availability: 'active' } },
      ], 5000)],
      metadata: { title: 'Product Spotlight', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_style_vote',
    name: 'Style Vote',
    type: 'poster',
    description: 'Vote on two styles',
    category: 'interactive',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a2e' } },
      pages: [page([
        { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.08, y: 0.15, payload: { text: 'Which style?', textStyle: 'headline', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('vote'), 2), type: 'vote', width: 0.7, height: 0.3, y: 0.55, payload: { question: 'Pick your favourite', options: [
          { id: createStableId('opt'), label: 'Option A' },
          { id: createStableId('opt'), label: 'Option B' },
        ] } },
      ], 7000)],
      metadata: { title: 'Style Vote', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_new_listing',
    name: 'New Listing',
    type: 'poster',
    description: 'Announce a new listing',
    category: 'announcement',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.8, height: 0.5, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.08, y: 0.7, payload: { text: 'Just Listed', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('product'), 3), type: 'product', width: 0.5, height: 0.1, y: 0.85, payload: { listingId: '', snapshotTitle: 'New Item', snapshotPriceGbp: 29, availability: 'active' } },
      ], 5000)],
      metadata: { title: 'New Listing', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_behind_scenes',
    name: 'Behind the Scenes',
    type: 'poster',
    description: 'Share a behind-the-scenes moment',
    category: 'story',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#0d0d0d' } },
      pages: [
        page([{ ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.7, y: 0.4, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } }], 3000),
        page([{ ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.1, payload: { text: 'Behind the Scenes', textStyle: 'editorial', textColor: '#ffffff', alignment: 'center', opacity: 1 } }], 3000),
      ],
      metadata: { title: 'Behind the Scenes', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_countdown_drop',
    name: 'Countdown Drop',
    type: 'poster',
    description: 'Build hype with a countdown',
    category: 'featured',
    build: () => {
      const endDate = new Date();
      endDate.setDate(endDate.getDate() + 3);
      endDate.setHours(18, 0, 0, 0);
      return {
        id: createStableId('doc'),
        type: 'poster',
        version: 1,
        canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a2e' } },
        pages: [page([
          { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.1, y: 0.2, payload: { text: 'Coming Soon', textStyle: 'headline', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.6, height: 0.09, y: 0.5, payload: { text: `Drops ${endDate.toLocaleDateString('en-GB', { weekday: 'long' })}`, textStyle: 'compact', textColor: '#1a1a2e', backgroundColor: '#C9A46A', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.7, height: 0.08, y: 0.8, payload: { text: 'Don\'t miss it', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        ], 7000)],
        metadata: { title: 'Countdown Drop', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 72, allowRemix: false },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
    },
  },
  {
    id: 'tpl_poster_quiz_trivia',
    name: 'Style Quiz',
    type: 'poster',
    description: 'Engage with a style quiz',
    category: 'interactive',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.08, y: 0.15, payload: { text: 'Guess the era', textStyle: 'headline', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('vote'), 2), type: 'vote', width: 0.75, height: 0.3, y: 0.55, payload: { question: 'When was this look popular?', options: [
          { id: createStableId('opt'), label: '1960s' },
          { id: createStableId('opt'), label: '1980s' },
          { id: createStableId('opt'), label: '2000s' },
        ] } },
      ], 8000)],
      metadata: { title: 'Style Quiz', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_qa_session',
    name: 'Q&A Session',
    type: 'poster',
    description: 'Invite questions from followers',
    category: 'interactive',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#9b0202' } },
      pages: [page([
        { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.1, y: 0.25, payload: { text: 'Ask Me Anything', textStyle: 'headline', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.09, y: 0.6, payload: { text: 'Drop your questions in replies', textStyle: 'compact', textColor: '#ffffff', backgroundColor: '#6B3245', alignment: 'center', opacity: 1 } },
      ], 10000)],
      metadata: { title: 'Q&A Session', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_emoji_react',
    name: 'React Slider',
    type: 'poster',
    description: 'Get vibe feedback with emoji slider',
    category: 'interactive',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#0d0d0d' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.5, y: 0.28, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.06, y: 0.62, payload: { text: 'How much do you love it?', textStyle: 'clean', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('vote'), 3), type: 'vote', width: 0.7, height: 0.18, y: 0.78, payload: { question: 'Rate this look', options: [
          { id: createStableId('opt'), label: '😍 Obsessed' },
          { id: createStableId('opt'), label: '😐 Meh' },
        ] } },
      ], 6000)],
      metadata: { title: 'React Slider', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_flash_sale',
    name: 'Flash Sale',
    type: 'poster',
    description: 'Time-sensitive sale announcement',
    category: 'sale',
    build: () => {
      const endDate = new Date();
      endDate.setHours(endDate.getHours() + 24);
      return {
        id: createStableId('doc'),
        type: 'poster',
        version: 1,
        canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#9b0202' } },
        pages: [page([
          { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.85, height: 0.12, y: 0.2, payload: { text: 'FLASH SALE', textStyle: 'poster', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.08, y: 0.38, payload: { text: '24 hours only', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.6, height: 0.09, y: 0.6, payload: { text: `Ends ${endDate.toLocaleDateString('en-GB', { weekday: 'long' })}`, textStyle: 'compact', textColor: '#1a1a2e', backgroundColor: '#C9A46A', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('product'), 4), type: 'product', width: 0.5, height: 0.1, y: 0.85, payload: { listingId: '', snapshotTitle: 'Shop Now', snapshotPriceGbp: 0, availability: 'active' } },
        ], 8000)],
        metadata: { title: 'Flash Sale', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
    },
  },
  {
    id: 'tpl_poster_multi_page_story',
    name: 'Story Sequence',
    type: 'poster',
    description: '3-page story with text and media',
    category: 'story',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a1a' } },
      pages: [
        page([{ ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.15, payload: { text: 'Once upon a time...', textStyle: 'editorial', textColor: '#C9A46A', alignment: 'center', opacity: 1 } }], 3000),
        page([{ ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.7, y: 0.4, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } }], 4000),
        page([
          { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.1, y: 0.3, payload: { text: 'The end', textStyle: 'signature', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('vote'), 2), type: 'vote', width: 0.6, height: 0.2, y: 0.65, payload: { question: 'Want more?', options: [
            { id: createStableId('opt'), label: 'Yes!' },
            { id: createStableId('opt'), label: 'No' },
          ] } },
        ], 5000),
      ],
      metadata: { title: 'Story Sequence', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  // ── Instagram parity: extended poster presets ─────────────────────
  {
    id: 'tpl_poster_poll_3',
    name: 'Poll 3',
    type: 'poster',
    description: 'Three-option poll template',
    category: 'interactive',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a2e' } },
      pages: [page([
        { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.08, y: 0.15, payload: { text: 'Which one?', textStyle: 'headline', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('vote'), 2), type: 'vote', width: 0.75, height: 0.35, y: 0.55, payload: { question: 'Pick your favourite', options: [
          { id: createStableId('opt'), label: 'Option A' },
          { id: createStableId('opt'), label: 'Option B' },
          { id: createStableId('opt'), label: 'Option C' },
        ] } },
      ], 5000)],
      metadata: { title: 'Poll 3', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_countdown_event',
    name: 'Countdown Event',
    type: 'poster',
    description: 'Event countdown with details',
    category: 'announcement',
    build: () => {
      const endDate = new Date();
      endDate.setDate(endDate.getDate() + 7);
      endDate.setHours(19, 0, 0, 0);
      return {
        id: createStableId('doc'),
        type: 'poster',
        version: 1,
        canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a2e' } },
        pages: [page([
          { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.1, y: 0.18, payload: { text: 'Event Night', textStyle: 'headline', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.65, height: 0.1, y: 0.5, payload: { text: `Starts ${endDate.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'short' })}`, textStyle: 'compact', textColor: '#1a1a2e', backgroundColor: '#C9A46A', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.7, height: 0.08, y: 0.82, payload: { text: 'Save the date', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        ], 7000)],
        metadata: { title: 'Countdown Event', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 168, allowRemix: false },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
    },
  },
  {
    id: 'tpl_poster_music_drop',
    name: 'Music Drop',
    type: 'poster',
    description: 'Album art with music sticker',
    category: 'featured',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#0d0d0d' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.7, height: 0.5, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.6, height: 0.09, y: 0.72, payload: { text: 'New Track — Artist', textStyle: 'compact', textColor: '#ffffff', backgroundColor: '#1a1a1a', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.7, height: 0.06, y: 0.88, payload: { text: 'Out now', textStyle: 'compact', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
      ], 15000)],
      metadata: { title: 'Music Drop', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_location_tag',
    name: 'Location Tag',
    type: 'poster',
    description: 'Location-focused story',
    category: 'story',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.7, y: 0.4, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.5, height: 0.08, y: 0.82, payload: { text: 'London, UK', textStyle: 'compact', textColor: '#ffffff', backgroundColor: '#1a1a1a', alignment: 'center', opacity: 1 } },
      ], 5000)],
      metadata: { title: 'Location Tag', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_hashtag_campaign',
    name: 'Hashtag Campaign',
    type: 'poster',
    description: 'Hashtag-focused campaign story',
    category: 'announcement',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#9b0202' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.5, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.6, height: 0.08, y: 0.68, payload: { text: '#ThryftFinds', textStyle: 'compact', textColor: '#1a1a2e', backgroundColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.7, height: 0.06, y: 0.85, payload: { text: 'Join the campaign', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
      ], 5000)],
      metadata: { title: 'Hashtag Campaign', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_behind_scenes_multi',
    name: 'Behind Scenes',
    type: 'poster',
    description: 'Three-page behind-the-scenes story',
    category: 'story',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#0d0d0d' } },
      pages: [
        page([
          { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.6, y: 0.35, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.08, y: 0.82, payload: { text: 'On set', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        ], 5000),
        page([
          { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.6, y: 0.35, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.08, y: 0.82, payload: { text: 'Getting ready', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        ], 5000),
        page([
          { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.9, height: 0.6, y: 0.35, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.08, y: 0.82, payload: { text: 'The final look', textStyle: 'compact', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        ], 5000),
      ],
      metadata: { title: 'Behind Scenes', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_tutorial_step',
    name: 'Tutorial Step',
    type: 'poster',
    description: 'Step-by-step tutorial with number',
    category: 'story',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.55, y: 0.32, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.15, height: 0.1, x: 0.15, y: 0.15, payload: { text: '1', textStyle: 'poster', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.7, height: 0.08, y: 0.82, payload: { text: 'Step one: prep', textStyle: 'clean', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
      ], 7000)],
      metadata: { title: 'Tutorial Step', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_testimonial',
    name: 'Testimonial',
    type: 'poster',
    description: 'Customer quote template',
    category: 'featured',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a2e' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.4, height: 0.4, x: 0.5, y: 0.25, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.8, height: 0.15, y: 0.6, payload: { text: '"Absolutely love it"', textStyle: 'editorial', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.6, height: 0.06, y: 0.82, payload: { text: '— Happy Customer', textStyle: 'signature', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
      ], 6000)],
      metadata: { title: 'Testimonial', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_before_after',
    name: 'Before After',
    type: 'poster',
    description: 'Two-page comparison template',
    category: 'story',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#0d0d0d' } },
      pages: [
        page([
          { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.6, y: 0.35, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.6, height: 0.08, y: 0.82, payload: { text: 'Before', textStyle: 'headline', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        ], 5000),
        page([
          { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.6, y: 0.35, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.6, height: 0.08, y: 0.82, payload: { text: 'After', textStyle: 'headline', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        ], 5000),
      ],
      metadata: { title: 'Before After', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_product_reveal',
    name: 'Product Reveal',
    type: 'poster',
    description: 'Three-page teaser reveal sequence',
    category: 'announcement',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a1a' } },
      pages: [
        page([
          { ...baseLayer(createStableId('text'), 1), type: 'text', width: 0.8, height: 0.12, payload: { text: 'Something is coming...', textStyle: 'headline', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        ], 5000),
        page([
          { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.65, y: 0.4, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.08, y: 0.85, payload: { text: 'Here it is', textStyle: 'headline', textColor: '#ffffff', alignment: 'center', opacity: 1 } },
        ], 5000),
        page([
          { ...baseLayer(createStableId('product'), 1), type: 'product', width: 0.6, height: 0.15, y: 0.4, payload: { listingId: '', snapshotTitle: 'New Arrival', snapshotPriceGbp: 39, availability: 'active' } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.7, height: 0.08, y: 0.7, payload: { text: 'Shop now', textStyle: 'compact', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        ], 5000),
      ],
      metadata: { title: 'Product Reveal', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_flash_sale_countdown',
    name: 'Flash Sale Countdown',
    type: 'poster',
    description: 'Flash sale with live countdown',
    category: 'sale',
    build: () => {
      const endDate = new Date();
      endDate.setHours(endDate.getHours() + 12);
      return {
        id: createStableId('doc'),
        type: 'poster',
        version: 1,
        canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#9b0202' } },
        pages: [page([
          { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.45, y: 0.25, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.85, height: 0.1, y: 0.55, payload: { text: 'FLASH SALE', textStyle: 'poster', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
          { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.6, height: 0.09, y: 0.78, payload: { text: `Ends ${endDate.toLocaleTimeString('en-GB', { hour: 'numeric' })}`, textStyle: 'compact', textColor: '#1a1a2e', backgroundColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        ], 10000)],
        metadata: { title: 'Flash Sale Countdown', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
    },
  },
  {
    id: 'tpl_poster_qa_round',
    name: 'Q&A Round',
    type: 'poster',
    description: 'Q&A session with question sticker',
    category: 'interactive',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.5625, background: { type: 'color', value: '#1a1a2e' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.85, height: 0.45, y: 0.25, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 2), type: 'text', width: 0.8, height: 0.08, y: 0.58, payload: { text: 'Ask me anything', textStyle: 'headline', textColor: '#C9A46A', alignment: 'center', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.7, height: 0.09, y: 0.8, payload: { text: 'Drop your questions in replies', textStyle: 'compact', textColor: '#ffffff', backgroundColor: '#6B3245', alignment: 'center', opacity: 1 } },
      ], 7000)],
      metadata: { title: 'Q&A Round', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 24, allowRemix: false },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  // ── Moodboard templates ──
  // Editorial collage-style posters for arranging multiple items into a
  // themed moodboard. These are part of the poster creative tooling —
  // users access them via the poster template browser's "Moodboard"
  // category. Each template provides a different collage layout.
  {
    id: 'tpl_poster_moodboard_grid',
    name: 'Moodboard Grid',
    type: 'poster',
    description: '2×2 editorial collage grid',
    category: 'moodboard',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 1, background: { type: 'color', value: '#f7f5f2' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.42, height: 0.42, x: 0.28, y: 0.28, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.42, height: 0.42, x: 0.72, y: 0.28, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.42, height: 0.42, x: 0.28, y: 0.72, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 4), type: 'media', width: 0.42, height: 0.42, x: 0.72, y: 0.72, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
      ], 0)],
      metadata: { title: 'Moodboard Grid', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: true },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_moodboard_editorial',
    name: 'Editorial Collage',
    type: 'poster',
    description: 'Asymmetric editorial collage with text',
    category: 'moodboard',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.8, background: { type: 'color', value: '#1a1a1a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.55, height: 0.6, x: 0.35, y: 0.3, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.3, height: 0.3, x: 0.78, y: 0.68, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 0.9 } },
        { ...baseLayer(createStableId('text'), 3), type: 'text', width: 0.5, height: 0.06, x: 0.3, y: 0.78, payload: { text: 'Season Edit', textStyle: 'headline', textColor: '#C9A46A', alignment: 'left', opacity: 1 } },
      ], 0)],
      metadata: { title: 'Editorial Collage', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: true },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_moodboard_collection',
    name: 'Collection Board',
    type: 'poster',
    description: 'Six-item collection moodboard',
    category: 'moodboard',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 1.2, background: { type: 'color', value: '#f0ede8' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.28, height: 0.28, x: 0.2, y: 0.22, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.28, height: 0.28, x: 0.5, y: 0.22, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.28, height: 0.28, x: 0.8, y: 0.22, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 4), type: 'media', width: 0.28, height: 0.28, x: 0.2, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 5), type: 'media', width: 0.28, height: 0.28, x: 0.5, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 6), type: 'media', width: 0.28, height: 0.28, x: 0.8, y: 0.5, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('text'), 7), type: 'text', width: 0.6, height: 0.05, x: 0.5, y: 0.82, payload: { text: 'Curated Collection', textStyle: 'compact', textColor: '#666666', alignment: 'center', opacity: 1 } },
      ], 0)],
      metadata: { title: 'Collection Board', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: true },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
  {
    id: 'tpl_poster_moodboard_inspiration',
    name: 'Inspiration Wall',
    type: 'poster',
    description: 'Scattered inspiration wall collage',
    category: 'moodboard',
    build: () => ({
      id: createStableId('doc'),
      type: 'poster',
      version: 1,
      canvas: { aspectRatio: 0.75, background: { type: 'color', value: '#2a2a2a' } },
      pages: [page([
        { ...baseLayer(createStableId('media'), 1), type: 'media', width: 0.4, height: 0.5, x: 0.3, y: 0.28, rotation: -0.05, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 1 } },
        { ...baseLayer(createStableId('media'), 2), type: 'media', width: 0.32, height: 0.4, x: 0.7, y: 0.32, rotation: 0.08, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 0.95 } },
        { ...baseLayer(createStableId('media'), 3), type: 'media', width: 0.28, height: 0.28, x: 0.28, y: 0.72, rotation: 0.04, payload: { mediaUri: '', mediaType: 'image', contentFit: 'cover', opacity: 0.9 } },
        { ...baseLayer(createStableId('text'), 4), type: 'text', width: 0.4, height: 0.05, x: 0.7, y: 0.78, payload: { text: 'Mood Board', textStyle: 'clean', textColor: '#C9A46A', alignment: 'right', opacity: 1 } },
      ], 0)],
      metadata: { title: 'Inspiration Wall', caption: '', visibility: 'public', allowReplies: true, allowReactions: true, expiresInHours: 48, allowRemix: true },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }),
  },
];
