/**
 * SSL Public-Key Pinning configuration for ThryftVerse.
 *
 * OWASP Mobile Top 10 (2024) — M4: Insecure Communication.
 *
 * Per OWASP guidance: pin the PUBLIC KEY (SPKI hash), not the certificate.
 * Certificates rotate; public keys are stable across renewals. Always keep a
 * backup pin so a key rotation does not brick the app.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * INSTALLATION (not yet installed — requires a development build, NOT Expo Go)
 * ────────────────────────────────────────────────────────────────────────────
 *
 *   npm install react-native-ssl-public-key-pinning
 *
 * Then create a development build (the native module cannot run in Expo Go):
 *
 *   eas build --profile development --platform ios
 *   eas build --profile development --platform android
 *
 * Initialise pinning as early as possible — before the first network request.
 * A good place is the app entry point (`index.ts` / `App.tsx` top-level effect):
 *
 *   import { initializeSslPinning } from '../utils/sslPinning';
 *   await initializeSslPinning();
 *
 * The `react-native-ssl-public-key-pinning` library patches the native
 * networking stack (OkHttp on Android, NSURLSession on iOS) so that *every*
 * HTTPS connection is validated against the pins — including fetch, Axios,
 * and image loaders.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * HOW TO COMPUTE A PIN
 * ────────────────────────────────────────────────────────────────────────────
 *
 * A pin is the base64-encoded SHA-256 hash of the DER-encoded SubjectPublicKeyInfo
 * (SPKI) of the leaf or intermediate certificate. Compute with OpenSSL:
 *
 *   openssl s_client -connect api.thryftverse.com:443 -showcerts 2>/dev/null \
 *     | openssl x509 -pubkey -noout \
 *     | openssl pkey -pubin -outform der \
 *     | openssl dgst -sha256 -binary \
 *     | openssl base64
 *
 * Repeat for the backup key (a different key pair held in reserve for rotation).
 *
 * ────────────────────────────────────────────────────────────────────────────
 * PRODUCTION ROLLOUT SAFETY
 * ────────────────────────────────────────────────────────────────────────────
 *
 * 1. Ship with pinning in ENFORCE mode only after a staged rollout confirms
 *    no false positives (e.g. corporate proxies, CDN edge changes).
 * 2. Keep at least one backup pin live at all times.
 * 3. Subscribe to certificate transparency / rotation alerts for the pinned
 *    domains so a key rotation is coordinated with an app update BEFORE the
 *    old pin expires.
 * 4. Expose a kill-switch via remote config (expo-updates runtime version) so
 *    a broken pin can be relaxed without a full store review cycle.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * PRODUCTION READINESS CHECKLIST (complete BEFORE flipping `enforce: true`)
 * ────────────────────────────────────────────────────────────────────────────
 *
 *   [ ] 1. Install the native module:
 *           npm install react-native-ssl-public-key-pinning
 *         Then create a development build (NOT Expo Go):
 *           eas build --profile development --platform ios
 *           eas build --profile development --platform android
 *
 *   [ ] 2. Compute REAL SPKI hashes for every pinned domain (see "HOW TO
 *         COMPUTE A PIN" above). Replace every PLACEHOLDER_* value in
 *         SSL_PINNING_CONFIG.domains with a real base64 SHA-256 SPKI hash.
 *
 *   [ ] 3. Verify at least one BACKUP pin per domain is live and corresponds
 *         to a DIFFERENT key pair held in reserve (rotation safety).
 *
 *   [ ] 4. Run a staged rollout with `enforce: false` first and inspect logs
 *         for pin-validation failures (corporate proxies, CDN edge changes,
 *         user-installed CAs). No false positives before proceeding.
 *
 *   [ ] 5. Flip `enforce: true` ONLY after the staged rollout is clean.
 *
 *   [ ] 6. Subscribe to certificate-transparency / key-rotation alerts so an
 *         upcoming rotation triggers an app update BEFORE the old pin expires.
 *
 *   [ ] 7. Confirm a remote kill-switch (expo-updates runtime version) is in
 *         place so a broken pin can be relaxed without a full store review.
 *
 * Until every box above is checked, `getSslPinningStatus()` will report a
 * non-`active` status and `isSslPinningEnabled()` returns `false`. Per
 * AGENTS.md §11 (Truthful UI) we never claim pinning is active when it is not.
 */

/**
 * Domains and their pinned public-key hashes (base64 SHA-256 of SPKI).
 *
 * ────────────────────────────────────────────────────────────────────────────
 * LOCAL DEV vs PRODUCTION HASH SELECTION
 * ────────────────────────────────────────────────────────────────────────────
 *
 * When `__DEV__` is true the config uses LOCAL DEV hashes derived from the
 * self-signed certificates generated by
 * `frontend/scripts/generate-local-spki-hashes.sh`. These let the app test
 * SSL public-key pinning end-to-end against the local Docker nginx-tls
 * proxy (`docker compose --profile tls up`).
 *
 * !!! LOCAL DEV ONLY — REPLACE FOR PRODUCTION !!!
 * The local dev hashes MUST NOT ship in a production build. When `__DEV__`
 * is false the config reads production hashes from the `EXPO_PUBLIC_SSL_PIN_*`
 * environment variables (set as EAS build secrets). If a production env var
 * is missing the pin falls back to the local dev hash so the build does not
 * crash, but `validate-ssl-pins.mjs` will fail a production build
 * (`EXPO_PUBLIC_ENVIRONMENT=production`) if any pin is still a local dev
 * default.
 *
 * BUILD-TIME VALIDATION: when `enforce` is flipped to `true`, the build MUST
 * fail if any hash still contains the PLACEHOLDER marker. A guard is provided
 * via `hasPlaceholderHashes()`; wire it into a pre-build script
 * (e.g. `scripts/validate-ssl-pins.mjs` invoked from package.json `prebuild`)
 * so a production build can never ship with placeholder pins in enforce mode.
 */

/**
 * LOCAL DEV SPKI SHA-256 hashes (base64).
 * LOCAL DEV ONLY — REPLACE FOR PRODUCTION.
 * Generated by frontend/scripts/generate-local-spki-hashes.sh from the
 * self-signed dev CA in docker/nginx/certs/. These match the hashes in
 * plugins/withTrustKit.js and plugins/withAndroidSecurityXml.js.
 */
const LOCAL_DEV_PINS: Record<string, SslPin> = {
  'api.thryftverse.com': {
    primary: 'Fb5JW02nuZPOD4wVU8nH+kr0jfWYj0EEmKbs1GiBVt0=',
    backup: 'q1gOabJwZJb8b6X5rZrGGzOstWkaJzr1elzO3XNwAeY=',
  },
  'cdn.thryftverse.com': {
    primary: 'VpPP8ycfh5u0OzPPQoQysNtalnE0WEXUJZZ/4/gU3Is=',
    backup: 'JP/p6hMm8Q8K/ieR8T/jMoAHQ6rABkLS3w/De5u9iPk=',
  },
  // Staging/dev reuse the API local dev hash so the same nginx-tls proxy
  // can serve all local pinning test traffic.
  'api-staging.thryftverse.com': {
    primary: 'Fb5JW02nuZPOD4wVU8nH+kr0jfWYj0EEmKbs1GiBVt0=',
    backup: 'q1gOabJwZJb8b6X5rZrGGzOstWkaJzr1elzO3XNwAeY=',
  },
};

/**
 * Maps a pinned domain to the short env-var suffix used by
 * withAndroidSecurityXml.js (e.g. `api.thryftverse.com` → `API`). This
 * keeps the runtime pin env vars consistent with the Android build-time
 * pin env vars: EXPO_PUBLIC_SSL_PIN_API_PRIMARY, etc.
 */
const DOMAIN_TO_ENV_SUFFIX: Record<string, string> = {
  'api.thryftverse.com': 'API',
  'cdn.thryftverse.com': 'CDN',
  'api-staging.thryftverse.com': 'STAGING',
  'api-dev.thryftverse.com': 'DEV',
};

/**
 * Reads a production SPKI hash from the `EXPO_PUBLIC_SSL_PIN_*` env vars.
 * Returns the local dev fallback when the env var is absent so a build
 * never crashes on a missing secret — the validate-ssl-pins.mjs guard
 * catches this in production builds.
 */
function readProductionPin(
  domain: string,
  kind: 'primary' | 'backup',
): string {
  const suffix = DOMAIN_TO_ENV_SUFFIX[domain] ?? domain.toUpperCase().replace(/[^A-Z0-9]/g, '_');
  const envKey = `EXPO_PUBLIC_SSL_PIN_${suffix}_${kind.toUpperCase()}`;
  const value = process.env[envKey];
  if (value && !value.startsWith('PLACEHOLDER_') && !value.startsWith('REPLACE_WITH_')) {
    return value;
  }
  // Fall back to the local dev hash. LOCAL DEV ONLY.
  return LOCAL_DEV_PINS[domain]?.[kind] ?? `PLACEHOLDER_${envKey}`;
}

export interface SslPin {
  /** Primary public-key hash (base64 SHA-256 of SPKI). */
  primary: string;
  /** Backup public-key hash — used during key rotation so the app is not bricked. */
  backup: string;
}

/**
 * Build the domain pin map. In `__DEV__` we use the LOCAL DEV hashes so
 * pinning can be tested against the Docker nginx-tls proxy. In production
 * builds we read the real SPKI hashes from EAS build secrets.
 */
function buildDomainPins(): Record<string, SslPin> {
  if (__DEV__) {
    return { ...LOCAL_DEV_PINS };
  }
  const domains = Object.keys(LOCAL_DEV_PINS);
  const pins: Record<string, SslPin> = {};
  for (const domain of domains) {
    pins[domain] = {
      primary: readProductionPin(domain, 'primary'),
      backup: readProductionPin(domain, 'backup'),
    };
  }
  return pins;
}

export const SSL_PINNING_CONFIG = {
  // When `false`, pin validation failures are logged but not blocked.
  // Set to `true` ONLY after the production readiness checklist above is
  // complete and a staged rollout confirms no false positives.
  enforce: false,
  domains: buildDomainPins() as Record<string, SslPin>,
} as const;

/** Marker prefix used to detect un-replaced placeholder hashes. */
const PLACEHOLDER_MARKER = 'PLACEHOLDER_';

/**
 * Returns `true` when any configured pin still contains a placeholder hash.
 * Used by `getSslPinningStatus()` and by build-time validation scripts.
 */
export function hasPlaceholderHashes(): boolean {
  return Object.values(SSL_PINNING_CONFIG.domains).some(
    (pin) =>
      pin.primary.includes(PLACEHOLDER_MARKER) ||
      pin.backup.includes(PLACEHOLDER_MARKER),
  );
}

/**
 * Truthful report of whether SSL pinning is actually enforced right now.
 *
 * Pinning is only considered enabled when ALL of the following are true:
 *   1. The native module `react-native-ssl-public-key-pinning` is installed.
 *   2. The config contains non-placeholder hashes.
 *   3. `SSL_PINNING_CONFIG.enforce` is `true`.
 *
 * Per AGENTS.md §11: this MUST return `false` unless pinning is genuinely
 * active. Never report a partial / configured-but-disabled state as enabled.
 */
export function isSslPinningEnabled(): boolean {
  return getSslPinningStatus() === 'active';
}

/**
 * Truthful, granular status of the SSL pinning configuration.
 *
 *   'active'                       — native module installed, real hashes, enforce=true.
 *   'configured-but-not-enforced'  — module installed + real hashes, but enforce=false.
 *   'placeholder-hashes'           — module installed, but hashes are still placeholders.
 *   'not-installed'                — native module is absent (pinning cannot run).
 *
 * Per AGENTS.md §11: every value reflects the real state. No value implies
 * protection that is not actually in place.
 */
export type SslPinningStatus =
  | 'active'
  | 'configured-but-not-enforced'
  | 'not-installed'
  | 'placeholder-hashes';

export function getSslPinningStatus(): SslPinningStatus {
  // The native module is intentionally optional. We detect it via a dynamic
  // import at init time, but for a synchronous status check we rely on a
  // module-level flag set by `initializeSslPinning()`. Before init runs we
  // conservatively report 'not-installed' (we cannot prove it is installed).
  if (!nativeModuleInstalled) {
    return 'not-installed';
  }
  if (hasPlaceholderHashes()) {
    return 'placeholder-hashes';
  }
  return SSL_PINNING_CONFIG.enforce ? 'active' : 'configured-but-not-enforced';
}

/**
 * Module-level flag flipped by `initializeSslPinning()` once the native module
 * is confirmed present. Defaults to `false` (unknown / not yet detected) so
 * `getSslPinningStatus()` is truthful before init has run.
 */
let nativeModuleInstalled = false;

/**
 * Initialise SSL public-key pinning.
 *
 * This is a NO-OP until `react-native-ssl-public-key-pinning` is installed and
 * a development build is created. The function is safe to call today — it
 * detects the missing native module and logs a warning instead of throwing.
 *
 * Per AGENTS.md §11: we do not claim pinning is active when it is not.
 */
export async function initializeSslPinning(): Promise<void> {
  try {
    // Dynamic import so the file compiles even when the package is absent.
    // @ts-expect-error — the package is intentionally optional; the .catch()
    // handles the runtime absence when the module is not installed.
    const mod = await import('react-native-ssl-public-key-pinning').catch(() => null);
    if (!mod) {
      nativeModuleInstalled = false;
      if (__DEV__) {
        console.warn(
          `[sslPinning] status: ${getSslPinningStatus()}. ` +
            'react-native-ssl-public-key-pinning is not installed — SSL pinning is NOT active. ' +
            'See frontend/src/utils/sslPinning.ts for setup.'
        );
      }
      return;
    }

    const init = (mod as { initialize?: (config: unknown) => Promise<void> }).initialize;
    if (typeof init !== 'function') {
      nativeModuleInstalled = false;
      if (__DEV__) {
        console.warn(
          `[sslPinning] status: ${getSslPinningStatus()}. ` +
            'Native module present but initialize() unavailable — pinning NOT active.'
        );
      }
      return;
    }

    nativeModuleInstalled = true;
    await init(SSL_PINNING_CONFIG);

    if (__DEV__) {
      // Log the truthful status after init so the console reflects exactly
      // what protection (if any) is in place. Per AGENTS.md §11 we never
      // claim pinning is active when it is not.
      console.info(`[sslPinning] status: ${getSslPinningStatus()}.`);
    }
  } catch (error) {
    nativeModuleInstalled = false;
    if (__DEV__) {
      console.warn(
        `[sslPinning] status: ${getSslPinningStatus()}. ` +
          'Initialisation failed — pinning NOT active.',
        error
      );
    }
  }
}
