/**
 * withTrustKit — Expo config plugin that injects TrustKit SSL pinning
 * configuration into the iOS Info.plist.
 *
 * TrustKit is an open-source iOS framework that implements SSL/TLS
 * public-key pinning on top of the native URLSession delegate system.
 * Unlike Android's network_security_config.xml, iOS does not support
 * SPKI pinning natively via Info.plist — TrustKit bridges that gap.
 *
 * This plugin adds the following Info.plist keys:
 *
 *   TSKSwizzleNetworkDelegates (bool)
 *     When true, TrustKit automatically swizzles the app's URLSession
 *     delegates to intercept SSL handshakes and verify pinned keys.
 *
 *   TSKPinnedDomains (dict)
 *     A dictionary of domains to pin, each containing:
 *       - TSKEnforcePinning (bool)   — block connections on pin mismatch
 *       - TSKIncludeSubdomains (bool) — pin all subdomains
 *       - TSKPublicKeyHashes (array)  — base64 SHA-256 SPKI hashes
 *       - TSKReportUris (array)       — URIs to report pin failures to
 *
 * Prerequisites:
 *   1. Install TrustKit in the iOS project (via Podfile or SPM).
 *      Expo managed workflow: add `trustkit` to the Podfile via a
 *      post-install hook, or use a dev client build that includes it.
 *   2. Set EXPO_PUBLIC_SSL_PINNING_ENABLED=true in the EAS build profile
 *      environment to activate this plugin.
 *
 * SPKI hash generation:
 *   See frontend/scripts/generate-spki-hashes.sh or run:
 *     openssl s_client -connect api.thryftverse.com:443 2>/dev/null \
 *       | openssl x509 -pubkey -noout \
 *       | openssl pkey -pubin -outform der \
 *       | openssl dgst -sha256 -binary \
 *       | openssl enc -base64
 *
 * @param {import('@expo/config-plugins').ConfigPlugin} config
 * @param {Object} [props]
 * @param {boolean} [props.enforcePinning] — whether to enforce pinning (production) or report-only (dev/staging)
 * @returns {import('@expo/config-plugins').ConfigPlugin}
 */
const { withInfoPlist } = require('@expo/config-plugins');

// ────────────────────────────────────────────────────────────────────────────
// SPKI SHA-256 hashes (base64).
//
// !!! LOCAL DEV ONLY — REPLACE FOR PRODUCTION !!!
// The hashes below are derived from self-signed certificates generated by
// frontend/scripts/generate-local-spki-hashes.sh. They let the app test SSL
// public-key pinning against the local Docker nginx-tls proxy
// (docker compose --profile tls up) but MUST be replaced with the real
// production SPKI hashes before any staging/production build.
//
// To generate production hashes, run against the live domain:
//   ./frontend/scripts/generate-spki-hashes.sh api.thryftverse.com
//   ./frontend/scripts/generate-spki-hashes.sh cdn.thryftverse.com
//
// These MUST match the hashes in
//   frontend/android/app/src/main/res/xml/network_security_config.xml
// (generated by plugins/withAndroidSecurityXml.js) and in
//   frontend/src/utils/sslPinning.ts (SSL_PINNING_CONFIG.domains).
// ────────────────────────────────────────────────────────────────────────────
const PINNED_DOMAINS = {
  'api.thryftverse.com': {
    // LOCAL DEV ONLY — replace with the real production SPKI SHA-256 hash.
    TSKPublicKeyHashes: [
      'Fb5JW02nuZPOD4wVU8nH+kr0jfWYj0EEmKbs1GiBVt0=',
      'q1gOabJwZJb8b6X5rZrGGzOstWkaJzr1elzO3XNwAeY=',
    ],
  },
  'cdn.thryftverse.com': {
    // LOCAL DEV ONLY — replace with the real production SPKI SHA-256 hash.
    TSKPublicKeyHashes: [
      'VpPP8ycfh5u0OzPPQoQysNtalnE0WEXUJZZ/4/gU3Is=',
      'JP/p6hMm8Q8K/ieR8T/jMoAHQ6rABkLS3w/De5u9iPk=',
    ],
  },
};

function withTrustKit(config, props = {}) {
  const enforcePinning = props.enforcePinning !== undefined ? props.enforcePinning : true;

  return withInfoPlist(config, (modConfig) => {
    const infoPlist = modConfig.modResults;

    // TSKSwizzleNetworkDelegates — TrustKit intercepts URLSession SSL
    // handshakes automatically without manual delegate wiring.
    infoPlist.TSKSwizzleNetworkDelegates = true;

    // Build TSKPinnedDomains with per-domain enforcement + subdomain config.
    const pinnedDomains = {};
    for (const [domain, domainConfig] of Object.entries(PINNED_DOMAINS)) {
      pinnedDomains[domain] = {
        TSKEnforcePinning: enforcePinning,
        TSKIncludeSubdomains: true,
        TSKPublicKeyHashes: domainConfig.TSKPublicKeyHashes,
        // TSKReportUris — endpoints where TrustKit reports pin validation
        // failures. Empty for now; configure a reporting endpoint in
        // production to monitor pin failure incidents.
        TSKReportUris: [],
      };
    }

    infoPlist.TSKPinnedDomains = pinnedDomains;

    return modConfig;
  });
}

module.exports = withTrustKit;
