/**
 * withAndroidSecurityXml — Expo config plugin that generates the three
 * Android XML resource files referenced by `app.config.js`:
 *
 *   - res/xml/network_security_config.xml  (SSL/TLS pinning + cleartext policy)
 *   - res/xml/backup_rules.xml             (fullBackupContent exclusions)
 *   - res/xml/data_extraction_rules.xml    (dataExtractionRules for API 31+)
 *
 * Why this plugin exists
 * ----------------------
 * Expo SDK 57 changed `expo prebuild` to clear and regenerate the
 * `android/` directory by default. Any XML file that exists only in the
 * checked-in `android/` tree and is NOT regenerated by a config plugin
 * will be silently deleted on the next `expo prebuild --clean` or EAS
 * Build. This plugin makes the three security/backup resources
 * reproducible from the repository alone.
 *
 * The plugin reads the SPKI pin values from environment variables so
 * that real production pins are injected at build time without being
 * committed to the repository. If a pin env var is absent the plugin
 * writes a placeholder and logs a warning — the `validate-ssl-pins.mjs`
 * script (wired into `verify:phase`) will fail the build if any
 * placeholder remains in a production build.
 *
 * Pin env vars (set as EAS secrets or .env):
 *   EXPO_PUBLIC_SSL_PIN_API_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_API_BACKUP
 *   EXPO_PUBLIC_SSL_PIN_CDN_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_CDN_BACKUP
 *   EXPO_PUBLIC_SSL_PIN_STAGING_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_STAGING_BACKUP
 *   EXPO_PUBLIC_SSL_PIN_DEV_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_DEV_BACKUP
 *
 * !!! LOCAL DEV ONLY !!!
 * When a pin env var is absent the plugin falls back to a LOCAL DEV hash
 * derived from the self-signed certificates generated by
 * frontend/scripts/generate-local-spki-hashes.sh. These let the app test
 * SSL pinning against the local Docker nginx-tls proxy but MUST be
 * replaced with real production SPKI hashes (via the env vars above) for
 * any staging/production build. The validate-ssl-pins.mjs guard will fail
 * a production build if the EXPO_PUBLIC_ENVIRONMENT=production env var is
 * set and any pin still resolves to a local dev default.
 *
 * @param {import('@expo/config-plugins').ConfigPlugin} config
 * @returns {import('@expo/config-plugins').ConfigPlugin}
 */
const { withDangerousMod, withAndroidManifest } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// ────────────────────────────────────────────────────────────────────────────
// LOCAL DEV DEFAULT SPKI SHA-256 hashes (base64).
// LOCAL DEV ONLY — REPLACE FOR PRODUCTION.
// Generated by frontend/scripts/generate-local-spki-hashes.sh from the
// self-signed dev CA in docker/nginx/certs/. These match the hashes in
// plugins/withTrustKit.js and src/utils/sslPinning.ts so the local
// nginx-tls proxy can be used for end-to-end pinning tests.
// ────────────────────────────────────────────────────────────────────────────
const LOCAL_DEV_HASHES = {
  EXPO_PUBLIC_SSL_PIN_API_PRIMARY: 'Fb5JW02nuZPOD4wVU8nH+kr0jfWYj0EEmKbs1GiBVt0=',
  EXPO_PUBLIC_SSL_PIN_API_BACKUP: 'q1gOabJwZJb8b6X5rZrGGzOstWkaJzr1elzO3XNwAeY=',
  EXPO_PUBLIC_SSL_PIN_CDN_PRIMARY: 'VpPP8ycfh5u0OzPPQoQysNtalnE0WEXUJZZ/4/gU3Is=',
  EXPO_PUBLIC_SSL_PIN_CDN_BACKUP: 'JP/p6hMm8Q8K/ieR8T/jMoAHQ6rABkLS3w/De5u9iPk=',
  // Staging/dev reuse the API local dev hash so the same nginx-tls proxy
  // can serve all local pinning test traffic.
  EXPO_PUBLIC_SSL_PIN_STAGING_PRIMARY: 'Fb5JW02nuZPOD4wVU8nH+kr0jfWYj0EEmKbs1GiBVt0=',
  EXPO_PUBLIC_SSL_PIN_STAGING_BACKUP: 'q1gOabJwZJb8b6X5rZrGGzOstWkaJzr1elzO3XNwAeY=',
  EXPO_PUBLIC_SSL_PIN_DEV_PRIMARY: 'Fb5JW02nuZPOD4wVU8nH+kr0jfWYj0EEmKbs1GiBVt0=',
  EXPO_PUBLIC_SSL_PIN_DEV_BACKUP: 'q1gOabJwZJb8b6X5rZrGGzOstWkaJzr1elzO3XNwAeY=',
};

function readPin(name) {
  const value = process.env[name];
  if (value && !value.startsWith('REPLACE_WITH_')) {
    return value;
  }
  // No env var set — fall back to the LOCAL DEV hash so local builds and
  // pinning tests work out of the box. LOCAL DEV ONLY.
  const devDefault = LOCAL_DEV_HASHES[name];
  if (devDefault) {
    return devDefault;
  }
  return `REPLACE_WITH_${name}`;
}

function buildNetworkSecurityConfig() {
  const apiPrimary = readPin('EXPO_PUBLIC_SSL_PIN_API_PRIMARY');
  const apiBackup = readPin('EXPO_PUBLIC_SSL_PIN_API_BACKUP');
  const cdnPrimary = readPin('EXPO_PUBLIC_SSL_PIN_CDN_PRIMARY');
  const cdnBackup = readPin('EXPO_PUBLIC_SSL_PIN_CDN_BACKUP');
  const stagingPrimary = readPin('EXPO_PUBLIC_SSL_PIN_STAGING_PRIMARY');
  const stagingBackup = readPin('EXPO_PUBLIC_SSL_PIN_STAGING_BACKUP');
  const devPrimary = readPin('EXPO_PUBLIC_SSL_PIN_DEV_PRIMARY');
  const devBackup = readPin('EXPO_PUBLIC_SSL_PIN_DEV_BACKUP');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecurityXml.js — do not edit the
     checked-in android/ copy directly; it will be overwritten on prebuild.
     Pin values come from EXPO_PUBLIC_SSL_PIN_* env vars. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">api.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="true">
            <pin digest="SHA-256">${apiPrimary}</pin>
            <pin digest="SHA-256">${apiBackup}</pin>
        </pin-set>
    </domain-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">cdn.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="true">
            <pin digest="SHA-256">${cdnPrimary}</pin>
            <pin digest="SHA-256">${cdnBackup}</pin>
        </pin-set>
    </domain-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">api-staging.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="false">
            <pin digest="SHA-256">${stagingPrimary}</pin>
            <pin digest="SHA-256">${stagingBackup}</pin>
        </pin-set>
    </domain-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">api-dev.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="false">
            <pin digest="SHA-256">${devPrimary}</pin>
            <pin digest="SHA-256">${devBackup}</pin>
        </pin-set>
    </domain-config>

    <debug-overrides>
        <!-- In debug builds (android:debuggable="true"), allow cleartext to
             any host so the Expo dev client can connect to the Metro bundler
             on the host machine's LAN IP (e.g. 192.168.x.x:8081) and the
             local API at 10.0.2.2:4000. This override does NOT apply to
             release/production builds. -->
        <base-config cleartextTrafficPermitted="true">
            <trust-anchors>
                <certificates src="system"/>
                <certificates src="user"/>
            </trust-anchors>
        </base-config>
    </debug-overrides>
</network-security-config>`;
}

const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecurityXml.js — fullBackupContent
     exclusions. Sensitive caches and keys must never be backed up to
     Google Drive. -->
<full-backup-content>
    <exclude domain="sharedpref" path="auth-snapshot"/>
    <exclude domain="sharedpref" path="thryftverse_secure_store"/>
    <exclude domain="sharedpref" path="mmkv.default"/>
    <exclude domain="file" path="wallet/"/>
    <exclude domain="file" path="payments/"/>
    <exclude domain="database" path="thryftverse.db"/>
</full-backup-content>`;

const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecurityXml.js — dataExtractionRules
     for Android 12+ (API 31+). Separates cloud-backup from
     device-to-device transfer rules. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="sharedpref" path="auth-snapshot"/>
        <exclude domain="sharedpref" path="thryftverse_secure_store"/>
        <exclude domain="sharedpref" path="mmkv.default"/>
        <exclude domain="file" path="wallet/"/>
        <exclude domain="file" path="payments/"/>
        <exclude domain="database" path="thryftverse.db"/>
    </cloud-backup>
    <device-transfer>
        <include domain="sharedpref" path="."/>
        <include domain="file" path="."/>
    </device-transfer>
</data-extraction-rules>`;

function withAndroidSecurityXml(config) {
  // First, write the XML resource files.
  config = withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const projectRoot = modConfig.modRequest.projectRoot;
      const resDir = path.join(
        projectRoot,
        'android',
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      if (!fs.existsSync(resDir)) {
        fs.mkdirSync(resDir, { recursive: true });
      }

      fs.writeFileSync(
        path.join(resDir, 'network_security_config.xml'),
        buildNetworkSecurityConfig(),
        'utf8',
      );
      fs.writeFileSync(
        path.join(resDir, 'backup_rules.xml'),
        BACKUP_RULES_XML,
        'utf8',
      );
      fs.writeFileSync(
        path.join(resDir, 'data_extraction_rules.xml'),
        DATA_EXTRACTION_RULES_XML,
        'utf8',
      );

      return modConfig;
    },
  ]);

  // Then, set the AndroidManifest.xml <application> attributes so the
  // generated XML files are actually referenced. Expo's config schema does
  // not support `android.networkSecurityConfig` as a first-class property,
  // and expo-secure-store overrides `fullBackupContent`/`dataExtractionRules`
  // with its own resource names. This withAndroidManifest call runs after
  // all config-level properties are applied, so it has the final say.
  config = withAndroidManifest(config, (manifestConfig) => {
    const application = manifestConfig.modResults.manifest?.application?.[0];
    if (application) {
      application.$['android:networkSecurityConfig'] =
        '@xml/network_security_config';
      application.$['android:fullBackupContent'] = '@xml/backup_rules';
      application.$['android:dataExtractionRules'] =
        '@xml/data_extraction_rules';
    }
    return manifestConfig;
  });

  return config;
}

module.exports = withAndroidSecurityXml;
