/**
 * withAndroidSecurityXml — Expo config plugin that generates the three
 * Android XML resource files referenced by `app.config.js`:
 *
 *   - res/xml/network_security_config.xml  (SSL/TLS pinning + cleartext policy)
 *   - res/xml/backup_rules.xml             (fullBackupContent exclusions)
 *   - res/xml/data_extraction_rules.xml    (dataExtractionRules for API 31+)
 *
 * Why this plugin exists
 * ----------------------
 * Expo SDK 57 changed `expo prebuild` to clear and regenerate the
 * `android/` directory by default. Any XML file that exists only in the
 * checked-in `android/` tree and is NOT regenerated by a config plugin
 * will be silently deleted on the next `expo prebuild --clean` or EAS
 * Build. This plugin makes the three security/backup resources
 * reproducible from the repository alone.
 *
 * The plugin reads the SPKI pin values from environment variables so
 * that real production pins are injected at build time without being
 * committed to the repository. If a pin env var is absent the plugin
 * writes a placeholder and logs a warning — the `validate-ssl-pins.mjs`
 * script (wired into `verify:phase`) will fail the build if any
 * placeholder remains in a production build.
 *
 * Pin env vars (set as EAS secrets or .env):
 *   EXPO_PUBLIC_SSL_PIN_API_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_API_BACKUP
 *   EXPO_PUBLIC_SSL_PIN_CDN_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_CDN_BACKUP
 *   EXPO_PUBLIC_SSL_PIN_STAGING_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_STAGING_BACKUP
 *   EXPO_PUBLIC_SSL_PIN_DEV_PRIMARY
 *   EXPO_PUBLIC_SSL_PIN_DEV_BACKUP
 *
 * @param {import('@expo/config-plugins').ConfigPlugin} config
 * @returns {import('@expo/config-plugins').ConfigPlugin}
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

function readPin(name) {
  const value = process.env[name];
  if (!value || value.startsWith('REPLACE_WITH_')) {
    return `REPLACE_WITH_${name}`;
  }
  return value;
}

function buildNetworkSecurityConfig() {
  const apiPrimary = readPin('EXPO_PUBLIC_SSL_PIN_API_PRIMARY');
  const apiBackup = readPin('EXPO_PUBLIC_SSL_PIN_API_BACKUP');
  const cdnPrimary = readPin('EXPO_PUBLIC_SSL_PIN_CDN_PRIMARY');
  const cdnBackup = readPin('EXPO_PUBLIC_SSL_PIN_CDN_BACKUP');
  const stagingPrimary = readPin('EXPO_PUBLIC_SSL_PIN_STAGING_PRIMARY');
  const stagingBackup = readPin('EXPO_PUBLIC_SSL_PIN_STAGING_BACKUP');
  const devPrimary = readPin('EXPO_PUBLIC_SSL_PIN_DEV_PRIMARY');
  const devBackup = readPin('EXPO_PUBLIC_SSL_PIN_DEV_BACKUP');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecurityXml.js — do not edit the
     checked-in android/ copy directly; it will be overwritten on prebuild.
     Pin values come from EXPO_PUBLIC_SSL_PIN_* env vars. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">api.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="true">
            <pin digest="SHA-256">${apiPrimary}</pin>
            <pin digest="SHA-256">${apiBackup}</pin>
        </pin-set>
    </domain-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">cdn.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="true">
            <pin digest="SHA-256">${cdnPrimary}</pin>
            <pin digest="SHA-256">${cdnBackup}</pin>
        </pin-set>
    </domain-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">api-staging.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="false">
            <pin digest="SHA-256">${stagingPrimary}</pin>
            <pin digest="SHA-256">${stagingBackup}</pin>
        </pin-set>
    </domain-config>

    <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">api-dev.thryftverse.com</domain>
        <pin-set expiration="2027-12-31" enforce="false">
            <pin digest="SHA-256">${devPrimary}</pin>
            <pin digest="SHA-256">${devBackup}</pin>
        </pin-set>
    </domain-config>

    <debug-overrides>
        <domain-config cleartextTrafficPermitted="true">
            <domain includeSubdomains="false">localhost</domain>
            <domain includeSubdomains="false">10.0.2.2</domain>
            <trust-anchors>
                <certificates src="system"/>
                <certificates src="user"/>
            </trust-anchors>
        </domain-config>
        <trust-anchors>
            <certificates src="system"/>
            <certificates src="user"/>
        </trust-anchors>
    </debug-overrides>
</network-security-config>`;
}

const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecurityXml.js — fullBackupContent
     exclusions. Sensitive caches and keys must never be backed up to
     Google Drive. -->
<full-backup-content>
    <exclude domain="sharedpref" path="auth-snapshot"/>
    <exclude domain="sharedpref" path="thryftverse_secure_store"/>
    <exclude domain="sharedpref" path="mmkv.default"/>
    <exclude domain="file" path="wallet/"/>
    <exclude domain="file" path="payments/"/>
    <exclude domain="database" path="thryftverse.db"/>
</full-backup-content>`;

const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidSecurityXml.js — dataExtractionRules
     for Android 12+ (API 31+). Separates cloud-backup from
     device-to-device transfer rules. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="sharedpref" path="auth-snapshot"/>
        <exclude domain="sharedpref" path="thryftverse_secure_store"/>
        <exclude domain="sharedpref" path="mmkv.default"/>
        <exclude domain="file" path="wallet/"/>
        <exclude domain="file" path="payments/"/>
        <exclude domain="database" path="thryftverse.db"/>
    </cloud-backup>
    <device-transfer>
        <include domain="sharedpref" path="."/>
        <include domain="file" path="."/>
    </device-transfer>
</data-extraction-rules>`;

function withAndroidSecurityXml(config) {
  return withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const projectRoot = modConfig.modRequest.projectRoot;
      const resDir = path.join(
        projectRoot,
        'android',
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      if (!fs.existsSync(resDir)) {
        fs.mkdirSync(resDir, { recursive: true });
      }

      fs.writeFileSync(
        path.join(resDir, 'network_security_config.xml'),
        buildNetworkSecurityConfig(),
        'utf8',
      );
      fs.writeFileSync(
        path.join(resDir, 'backup_rules.xml'),
        BACKUP_RULES_XML,
        'utf8',
      );
      fs.writeFileSync(
        path.join(resDir, 'data_extraction_rules.xml'),
        DATA_EXTRACTION_RULES_XML,
        'utf8',
      );

      return modConfig;
    },
  ]);
}

module.exports = withAndroidSecurityXml;
