/**
 * Locale registry + string resolution — the web i18n source of truth.
 *
 * Locale modules are generated by `scripts/sync-locales.mjs` from
 * `frontend/src/i18n/locales/*.json` (the mobile source of truth).
 * `en` is canonical and defines the `Messages` schema; every other locale
 * is a `DeepPartial<Messages>` — missing keys resolve to en at lookup
 * time, matching mobile's coverage honestly (e.g. `stateCopy` domain
 * strings ship in en only, exactly as on mobile).
 *
 * Lookup contract:
 *   t('chrome.nav.explore')           → dotted path into Messages
 *   t('key', { count })               → interpolates {x} and {{x}}
 *   count present + `<key>_one` etc.  → Intl.PluralRules category lookup
 *                                       (i18next `_one`/`_other` convention)
 */
import { en } from './locales/en';
import { ar } from './locales/ar';
import { de } from './locales/de';
import { es } from './locales/es';
import { fr } from './locales/fr';
import { hi } from './locales/hi';
import { id } from './locales/id';
import { ja } from './locales/ja';
import { ko } from './locales/ko';
import { pt } from './locales/pt';
import { ru } from './locales/ru';
import { tr } from './locales/tr';
import { zh } from './locales/zh';

export type Messages = typeof en;

export type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends string ? string : T[K] extends object ? DeepPartial<T[K]> : T[K];
};

export type Locale = 'en' | 'ar' | 'de' | 'es' | 'fr' | 'hi' | 'id' | 'ja' | 'ko' | 'pt' | 'ru' | 'tr' | 'zh';

export interface LocaleMeta {
  code: Locale;
  /** Endonym — the label shown in the language picker. */
  label: string;
  dir: 'ltr' | 'rtl';
}

export const LOCALES: readonly LocaleMeta[] = [
  { code: 'en', label: 'English', dir: 'ltr' },
  { code: 'ar', label: 'العربية', dir: 'rtl' },
  { code: 'de', label: 'Deutsch', dir: 'ltr' },
  { code: 'es', label: 'Español', dir: 'ltr' },
  { code: 'fr', label: 'Français', dir: 'ltr' },
  { code: 'hi', label: 'हिन्दी', dir: 'ltr' },
  { code: 'id', label: 'Bahasa Indonesia', dir: 'ltr' },
  { code: 'ja', label: '日本語', dir: 'ltr' },
  { code: 'ko', label: '한국어', dir: 'ltr' },
  { code: 'pt', label: 'Português', dir: 'ltr' },
  { code: 'ru', label: 'Русский', dir: 'ltr' },
  { code: 'tr', label: 'Türkçe', dir: 'ltr' },
  { code: 'zh', label: '中文', dir: 'ltr' },
];

export const DEFAULT_LOCALE: Locale = 'en';
export const LOCALE_STORAGE_KEY = 'thryftverse.web.locale';

export const MESSAGES: Record<Locale, DeepPartial<Messages>> = {
  en, ar, de, es, fr, hi, id, ja, ko, pt, ru, tr, zh,
};

export function isLocale(value: unknown): value is Locale {
  return typeof value === 'string' && LOCALES.some((l) => l.code === value);
}

export function localeDir(locale: Locale): 'ltr' | 'rtl' {
  return LOCALES.find((l) => l.code === locale)?.dir ?? 'ltr';
}

export type TParams = Record<string, string | number>;

function lookup(tree: unknown, key: string): string | undefined {
  let node: unknown = tree;
  for (const part of key.split('.')) {
    if (node == null || typeof node !== 'object') return undefined;
    node = (node as Record<string, unknown>)[part];
  }
  return typeof node === 'string' ? node : undefined;
}

function interpolate(template: string, params?: TParams): string {
  if (!params) return template;
  return template.replace(/\{\{?\s*(\w+)\s*\}?\}/g, (match, name: string) =>
    params[name] !== undefined ? String(params[name]) : match,
  );
}

const pluralRulesCache = new Map<Locale, Intl.PluralRules>();

function pluralCategory(locale: Locale, count: number): Intl.LDMLPluralRule {
  let rules = pluralRulesCache.get(locale);
  if (!rules) {
    rules = new Intl.PluralRules(locale);
    pluralRulesCache.set(locale, rules);
  }
  return rules.select(count);
}

/** True when the key resolves in the locale or the en fallback — for
 *  optional-key probes (state-copy registry) that must not trip the
 *  missing-key dev warning in `translate`. */
export function hasTranslation(locale: Locale, key: string): boolean {
  const messages = MESSAGES[locale] ?? MESSAGES.en;
  return lookup(messages, key) !== undefined || lookup(MESSAGES.en, key) !== undefined;
}

/**
 * Pure resolver — usable outside React (imperative code, tests).
 * Falls back to en when the locale lacks the key; returns the key itself
 * when en lacks it too (a missing key is never silently blank).
 */
export function translate(locale: Locale, key: string, params?: TParams): string {
  const messages = MESSAGES[locale] ?? MESSAGES.en;

  // Plural resolution first when a count is supplied: `<key>_<category>`
  // (Intl.PluralRules → zero/one/two/few/many/other per locale) then
  // `<key>_other`, matching the i18next convention the mobile files use.
  if (params?.count !== undefined) {
    const count = Number(params.count);
    const category = pluralCategory(locale, count);
    const pluralKey =
      lookup(messages, `${key}_${category}`) ??
      lookup(messages, `${key}_other`) ??
      lookup(MESSAGES.en, `${key}_${category}`) ??
      lookup(MESSAGES.en, `${key}_other`);
    if (pluralKey !== undefined) return interpolate(pluralKey, params);
    // Fall through to the plain key — some strings carry {count} inline.
  }

  const value = lookup(messages, key) ?? lookup(MESSAGES.en, key);
  if (value === undefined) {
    if (typeof process !== 'undefined' && process.env.NODE_ENV !== 'production') {
      console.warn(`[i18n] missing key "${key}" (locale ${locale}, en fallback absent)`);
    }
    return key;
  }
  return interpolate(value, params);
}
