-- @noTransaction
-- PostgreSQL production tuning.
--
-- In Docker dev, tuning is applied via the postgres command-line args
-- in docker-compose.yml (shared_buffers, work_mem, etc.).
--
-- In production, apply these settings via postgresql.conf or by running
-- ALTER SYSTEM as a superuser manually. This migration is a no-op to
-- avoid requiring superuser privileges in the app role.
--
-- Idempotent: this migration does nothing and is safe to run multiple times.
SELECT 1 AS postgres_tuning_skipped;
