-- Migration 207: Creator document presence and C2PA content credentials.
--
-- P2.13: Live presence for creator documents. Presence is ephemeral —
-- it is never saved as an edit. The user_presence table (migration 117)
-- already tracks socket-level presence; this migration adds a
-- creator_document_presence table for document-scoped presence with
-- the user's current activity (viewing, editing).
--
-- P2.14: C2PA 2.4 content credentials. The media_assets table already
-- has a metadata JSONB column; this migration adds a dedicated
-- media_content_credentials table for C2PA assertion manifests,
-- keeping the credential data separate from general metadata.

-- ── Creator document presence (ephemeral) ────────────────────────────
CREATE TABLE IF NOT EXISTS creator_document_presence (
  document_id TEXT NOT NULL REFERENCES creator_documents(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  socket_id TEXT NOT NULL,
  activity TEXT NOT NULL DEFAULT 'viewing'
    CHECK (activity IN ('viewing', 'editing', 'idle')),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (document_id, user_id, socket_id)
);

CREATE INDEX IF NOT EXISTS creator_document_presence_doc_idx
  ON creator_document_presence (document_id, last_seen_at DESC)
  WHERE last_seen_at > NOW() - INTERVAL '5 minutes';

-- ── C2PA content credentials ─────────────────────────────────────────
-- Stores C2PA 2.4 assertion manifests for media assets. Each row is an
-- immutable content credential that can be verified by external tools.
-- The manifest is the signed C2PA claim; the assertions are the
-- individual claims (ai-disclosure, source, edit actions, etc.).
CREATE TABLE IF NOT EXISTS media_content_credentials (
  id TEXT PRIMARY KEY,
  media_asset_id TEXT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
  -- The C2PA manifest JSON (the signed claim bundle)
  manifest JSONB NOT NULL,
  -- C2PA spec version (e.g. "2.4")
  spec_version TEXT NOT NULL DEFAULT '2.4',
  -- The claim generator identifier (e.g. "ThryftVerse/1.0")
  claim_generator TEXT NOT NULL DEFAULT 'ThryftVerse',
  -- Whether this credential was generated by the platform or imported
  source TEXT NOT NULL DEFAULT 'platform'
    CHECK (source IN ('platform', 'imported', 'third_party')),
  -- The assertions present in the manifest (for quick querying)
  assertion_types TEXT[] NOT NULL DEFAULT '{}',
  -- Whether the manifest includes an AI disclosure assertion
  has_ai_disclosure BOOLEAN NOT NULL DEFAULT FALSE,
  -- Verification status
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at TIMESTAMPTZ,
  -- The signing certificate fingerprint (if signed)
  signature_fingerprint TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (media_asset_id, spec_version)
);

CREATE INDEX IF NOT EXISTS media_content_credentials_asset_idx
  ON media_content_credentials (media_asset_id);

CREATE INDEX IF NOT EXISTS media_content_credentials_ai_idx
  ON media_content_credentials (has_ai_disclosure)
  WHERE has_ai_disclosure = TRUE;

COMMENT ON TABLE creator_document_presence IS
  'Ephemeral presence for creator documents. Tracks who is viewing/editing a document in real time. Never saved as an edit.';
COMMENT ON TABLE media_content_credentials IS
  'C2PA 2.4 content credentials for media assets. Stores signed assertion manifests for provenance and AI disclosure.';
